import React,{useEffect,useMemo,useState}from"react";
import{supabase}from"../supabaseClient";
import{Button,Field,Notice,Panel,friendlyError,inputStyle,money}from"./ui";

const LABEL={draft:"مسودة",submitted:"بانتظار الاعتماد",approved:"معتمد",rejected:"مرفوض",converted:"تم التحويل إلى أمر شراء",completed:"مكتمل",received:"عرض مستلم",selected:"مختار",partially_received:"استلام جزئي",fully_received:"مستلم بالكامل",invoiced:"مفوتر",sent:"مرسل للمورد"};
const REQUEST_STAGES=[
 {status:"draft",title:"Draft — مسودة",empty:"لا توجد مسودات."},
 {status:"submitted",title:"Pending Approval — بانتظار الاعتماد",empty:"لا توجد طلبات بانتظار الاعتماد."},
 {status:"approved",title:"Approved — معتمد",empty:"لا توجد طلبات معتمدة."},
 {status:"converted",title:"Converted To PO — محول إلى أمر شراء",empty:"لا توجد طلبات محولة."},
 {status:"completed",title:"Completed — مكتمل",empty:"لا توجد طلبات مكتملة."},
 {status:"rejected",title:"Rejected — مرفوض",empty:"لا توجد طلبات مرفوضة."}
];
const emptyWorkspace={requests:[],request_items:[],request_history:[],quotes:[],quote_items:[],orders:[],order_items:[],receipts:[],receipt_items:[],invoices:[],invoice_lines:[],capabilities:{}};
const cardStyle={border:"1px solid var(--color-border)",borderRadius:10,padding:10,display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"};
const overlayStyle={position:"fixed",inset:0,background:"rgba(0,0,0,.45)",display:"grid",placeItems:"center",zIndex:1000,padding:18};
const modalStyle={background:"var(--color-surface)",color:"var(--color-text)",borderRadius:14,padding:20,width:"min(100%,980px)",maxHeight:"90vh",overflow:"auto",boxShadow:"0 24px 80px rgba(0,0,0,.35)"};
const gridStyle={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,margin:"12px 0"};

function Info({label,value}){return <div><small style={{color:"var(--color-text-muted)"}}>{label}</small><div><strong>{value??"—"}</strong></div></div>}
function Table({headers,children}){return <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{headers.map(h=><th key={h} style={{textAlign:"right",padding:8,borderBottom:"1px solid var(--color-border)"}}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children}){return <td style={{padding:8,borderBottom:"1px solid var(--color-border)"}}>{children}</td>}

export function ProcurementWorkspace({data}){
 const[ws,setWs]=useState(emptyWorkspace),[inventory,setInventory]=useState({warehouses:[]});
 const[error,setError]=useState(""),[ok,setOk]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[rejecting,setRejecting]=useState(null),[rejectReason,setRejectReason]=useState("");
 const[request,setRequest]=useState({project_id:"",material_id:"",description:"",quantity:"",unit:"قطعة",estimated_unit_cost:"",justification:""});
 const[quote,setQuote]=useState({request_id:"",supplier_id:"",unit_price:"",currency:"SAR"});
 const[receipt,setReceipt]=useState({order_id:"",warehouse_id:"",delivery_ref:""});
 const[invoice,setInvoice]=useState({order_id:"",invoice_number:"",invoice_date:new Date().toISOString().slice(0,10)});

 async function load(){setLoading(true);setError("");const[p,i]=await Promise.all([supabase.rpc("get_procurement_workspace_v2",{target_project:null}),supabase.rpc("get_inventory_workspace")]);if(p.error)setError(friendlyError(p.error));else setWs({...emptyWorkspace,...(p.data||{})});if(i.error)setError(current=>current||friendlyError(i.error));else setInventory(i.data||{warehouses:[]});setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function call(name,args,msg){setError("");setOk("");const{error}=await supabase.rpc(name,args);if(error)return setError(friendlyError(error));setOk(msg);setSelected(null);setRejecting(null);setRejectReason("");await load()}
 async function saveRequest(){if(!request.description.trim()||Number(request.quantity)<=0)return setError("أدخل وصفًا وكمية صحيحة.");await call("save_purchase_request",{payload:{project_id:request.project_id||null,required_date:null,priority:"normal",justification:request.justification,items:[{material_id:request.material_id||null,description:request.description,quantity:Number(request.quantity),unit:request.unit,estimated_unit_cost:Number(request.estimated_unit_cost||0),sequence:1}]}},"تم حفظ طلب الشراء كمسودة.")}
 async function saveQuote(){const items=ws.request_items.filter(i=>i.purchase_request_id===quote.request_id);if(!quote.request_id||!quote.supplier_id||!items.length)return setError("اختر طلبًا معتمدًا وموردًا.");await call("save_supplier_quote",{payload:{purchase_request_id:quote.request_id,supplier_id:quote.supplier_id,supplier_reference:null,quote_date:new Date().toISOString().slice(0,10),currency:quote.currency,payment_terms:null,delivery_days:null,items:items.map(i=>({purchase_request_item_id:i.id,quantity:Number(i.quantity),unit_price:Number(quote.unit_price||0),discount_amount:0,tax_amount:0}))}},"تم تسجيل عرض المورد.")}
 async function receiveOrder(){if(!receipt.order_id||!receipt.warehouse_id)return setError("اختر أمر الشراء والمخزن المستلم.");const items=ws.order_items.filter(i=>i.purchase_order_id===receipt.order_id&&Number(i.received_quantity)<Number(i.quantity));if(!items.length)return setError("لا توجد كميات متبقية للاستلام.");await call("confirm_goods_receipt_to_inventory",{payload:{purchase_order_id:receipt.order_id,supplier_delivery_reference:receipt.delivery_ref,notes:null,items:items.map(i=>({purchase_order_item_id:i.id,quantity_received:Number(i.quantity)-Number(i.received_quantity),accepted_quantity:Number(i.quantity)-Number(i.received_quantity),condition:"accepted"}))},target_warehouse:receipt.warehouse_id,target_location:null},"تم تأكيد الاستلام وترحيل الكميات للمخزون في عملية واحدة.")}
 async function approveInvoice(){const order=ws.orders.find(o=>o.id===invoice.order_id),items=ws.order_items.filter(i=>i.purchase_order_id===invoice.order_id);if(!order||!invoice.invoice_number||!items.length)return setError("اختر أمر شراء وأدخل رقم الفاتورة.");await call("approve_supplier_invoice",{payload:{invoice_number:invoice.invoice_number,purchase_order_id:invoice.order_id,invoice_date:invoice.invoice_date,due_date:null,notes:null,items:items.map(i=>({purchase_order_item_id:i.id,goods_receipt_item_id:null,description:i.description,quantity:Number(i.quantity),unit_price:Number(i.unit_price),discount_amount:Number(i.discount_amount||0),tax_amount:Number(i.tax_amount||0),budget_item_id:i.budget_item_id||null,milestone_id:i.milestone_id||null}))}},"تم اعتماد الفاتورة وتسجيل التكلفة الفعلية مرة واحدة.")}
 function projectName(id){const p=data.projects.find(x=>x.id===id);return p?.project_name||p?.name||"بدون مشروع"}
 function supplierName(id){return data.suppliers.find(x=>x.id===id)?.name||"—"}
 function openRequest(row){setSelected({type:"request",row})}
 function openOrder(row){setSelected({type:"order",row})}
 function printDocument(){window.print()}

 const requestGroups=useMemo(()=>Object.fromEntries(REQUEST_STAGES.map(stage=>[stage.status,ws.requests.filter(r=>r.status===stage.status)])),[ws.requests]);
 const approvedRequests=ws.requests.filter(r=>r.status==="approved"),receivedQuotes=ws.quotes.filter(q=>["received","selected"].includes(q.status)),receivableOrders=ws.orders.filter(o=>["approved","sent","partially_received"].includes(o.status)),invoiceableOrders=ws.orders.filter(o=>["partially_received","fully_received"].includes(o.status));
 const selectedItems=useMemo(()=>!selected?[]:selected.type==="request"?ws.request_items.filter(i=>i.purchase_request_id===selected.row.id):ws.order_items.filter(i=>i.purchase_order_id===selected.row.id),[selected,ws]);
 const selectedHistory=useMemo(()=>selected?.type==="request"?ws.request_history.filter(h=>h.purchase_request_id===selected.row.id):[],[selected,ws.request_history]);
 const selectedReceipts=selected?.type==="order"?ws.receipts.filter(r=>r.purchase_order_id===selected.row.id):[];
 const selectedInvoices=selected?.type==="order"?ws.invoices.filter(i=>i.purchase_order_id===selected.row.id):[];

 function RequestCard({row}){return <div style={cardStyle}><span><strong>{row.request_number}</strong> — {LABEL[row.status]||row.status}<br/><small>{projectName(row.project_id)} · {row.required_date||"بدون تاريخ مطلوب"}</small></span><span style={{display:"flex",gap:6,flexWrap:"wrap"}}><Button onClick={()=>openRequest(row)}>فتح التفاصيل</Button>{row.status==="draft"&&<Button onClick={()=>call("submit_purchase_request",{target_id:row.id},"تم إرسال الطلب للاعتماد.")}>إرسال</Button>}</span></div>}

 return <div><h2>المشتريات والتوريد</h2><p style={{color:"var(--color-text-muted)"}}>المسار المعتمد: مسودة ← بانتظار الاعتماد ← معتمد ← محول إلى أمر شراء ← مكتمل، أو مرفوض مع تسجيل السبب.</p>
 {error&&<Notice type="error">{error}</Notice>}{ok&&<Notice>{ok}</Notice>}
 {loading?<Notice>جارِ تحميل دورة المشتريات...</Notice>:<>
  <Panel title="طلب شراء جديد"><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><Field label="المشروع"><select style={inputStyle} value={request.project_id} onChange={e=>setRequest({...request,project_id:e.target.value})}><option value="">بدون مشروع</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.project_name||p.name}</option>)}</select></Field><Field label="المادة"><select style={inputStyle} value={request.material_id} onChange={e=>setRequest({...request,material_id:e.target.value})}><option value="">اختر</option>{data.materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="الوصف"><input style={inputStyle} value={request.description} onChange={e=>setRequest({...request,description:e.target.value})}/></Field><Field label="الكمية"><input type="number" style={inputStyle} value={request.quantity} onChange={e=>setRequest({...request,quantity:e.target.value})}/></Field><Field label="تكلفة تقديرية"><input type="number" style={inputStyle} value={request.estimated_unit_cost} onChange={e=>setRequest({...request,estimated_unit_cost:e.target.value})}/></Field><Button onClick={saveRequest}>حفظ المسودة</Button></div></Panel>
  <Panel title="طلبات الشراء حسب المرحلة"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}>{REQUEST_STAGES.map(stage=><section key={stage.status} data-request-stage={stage.status} style={{border:"1px solid var(--color-border)",borderRadius:12,padding:12,background:"var(--color-surface-muted)"}}><h3 style={{marginTop:0,fontSize:16}}>{stage.title} ({requestGroups[stage.status]?.length||0})</h3><div style={{display:"grid",gap:8}}>{requestGroups[stage.status]?.map(r=><RequestCard key={r.id} row={r}/>)}{!requestGroups[stage.status]?.length&&<small>{stage.empty}</small>}</div></section>)}</div></Panel>
  {ws.capabilities.quote&&<Panel title="تسجيل عرض مورد"><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><Field label="الطلب المعتمد"><select style={inputStyle} value={quote.request_id} onChange={e=>setQuote({...quote,request_id:e.target.value})}><option value="">اختر</option>{approvedRequests.map(r=><option key={r.id} value={r.id}>{r.request_number}</option>)}</select></Field><Field label="المورد"><select style={inputStyle} value={quote.supplier_id} onChange={e=>setQuote({...quote,supplier_id:e.target.value})}><option value="">اختر</option>{data.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="سعر الوحدة"><input type="number" style={inputStyle} value={quote.unit_price} onChange={e=>setQuote({...quote,unit_price:e.target.value})}/></Field><Button onClick={saveQuote}>حفظ العرض</Button></div></Panel>}
  {ws.capabilities.order&&<Panel title="عروض الموردين"><div style={{display:"grid",gap:8}}>{receivedQuotes.map(q=><div key={q.id} style={cardStyle}><span>{q.quote_number} — {supplierName(q.supplier_id)} — {LABEL[q.status]||q.status}</span>{q.status==="received"&&<Button onClick={()=>call("create_purchase_order_from_quote",{target_quote:q.id},"تم إنشاء أمر الشراء.")}>إنشاء أمر شراء</Button>}</div>)}{!receivedQuotes.length&&<span>لا توجد عروض مستلمة.</span>}</div></Panel>}
  <Panel title="أوامر الشراء"><div style={{display:"grid",gap:8}}>{ws.orders.map(o=><div key={o.id} style={cardStyle}><span><strong>{o.order_number}</strong> — {LABEL[o.status]||o.status}<br/><small>{supplierName(o.supplier_id)} · {projectName(o.project_id)} · {money(o.total_amount)}</small></span><Button onClick={()=>openOrder(o)}>فتح التفاصيل</Button></div>)}{!ws.orders.length&&<span>لا توجد أوامر شراء.</span>}</div></Panel>
  {ws.capabilities.receive&&<Panel title="تأكيد الاستلام والترحيل للمخزون"><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><Field label="أمر الشراء"><select style={inputStyle} value={receipt.order_id} onChange={e=>setReceipt({...receipt,order_id:e.target.value})}><option value="">اختر</option>{receivableOrders.map(o=><option key={o.id} value={o.id}>{o.order_number}</option>)}</select></Field><Field label="المخزن"><select style={inputStyle} value={receipt.warehouse_id} onChange={e=>setReceipt({...receipt,warehouse_id:e.target.value})}><option value="">اختر</option>{inventory.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="مرجع التسليم"><input style={inputStyle} value={receipt.delivery_ref} onChange={e=>setReceipt({...receipt,delivery_ref:e.target.value})}/></Field><Button onClick={receiveOrder}>استلام وترحيل</Button></div></Panel>}
  {ws.capabilities.invoice&&<Panel title="اعتماد فاتورة المورد"><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><Field label="أمر الشراء المستلم"><select style={inputStyle} value={invoice.order_id} onChange={e=>setInvoice({...invoice,order_id:e.target.value})}><option value="">اختر</option>{invoiceableOrders.map(o=><option key={o.id} value={o.id}>{o.order_number}</option>)}</select></Field><Field label="رقم الفاتورة"><input style={inputStyle} value={invoice.invoice_number} onChange={e=>setInvoice({...invoice,invoice_number:e.target.value})}/></Field><Field label="تاريخ الفاتورة"><input type="date" style={inputStyle} value={invoice.invoice_date} onChange={e=>setInvoice({...invoice,invoice_date:e.target.value})}/></Field><Button onClick={approveInvoice}>اعتماد الفاتورة</Button></div></Panel>}
 </>}
 {selected&&<div style={overlayStyle}><div style={modalStyle} className="procurement-print-document"><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><h3 style={{marginTop:0}}>{selected.type==="request"?"تفاصيل طلب الشراء":"تفاصيل أمر الشراء"}</h3><strong>{selected.type==="request"?selected.row.request_number:selected.row.order_number}</strong></div><div style={{display:"flex",gap:6}}><Button onClick={printDocument}>طباعة / PDF</Button><Button onClick={()=>setSelected(null)}>إغلاق</Button></div></div>
  <div style={gridStyle}><Info label="الحالة" value={LABEL[selected.row.status]||selected.row.status}/><Info label="المشروع" value={projectName(selected.row.project_id)}/><Info label="تاريخ الإنشاء" value={(selected.row.created_at||"").slice(0,10)}/>{selected.type==="request"?<><Info label="الأولوية" value={selected.row.priority}/><Info label="التاريخ المطلوب" value={selected.row.required_date||"—"}/><Info label="مبرر الطلب" value={selected.row.justification||"—"}/></>:<><Info label="المورد" value={supplierName(selected.row.supplier_id)}/><Info label="تاريخ الأمر" value={selected.row.order_date}/><Info label="التسليم المتوقع" value={selected.row.expected_delivery_date||"—"}/><Info label="شروط الدفع" value={selected.row.payment_terms||"—"}/></>}</div>
  <Table headers={selected.type==="request"?["الوصف","الكمية","الوحدة","تكلفة الوحدة التقديرية","الإجمالي"]:["الوصف","المطلوب","المستلم","سعر الوحدة","الخصم","الضريبة","الإجمالي"]}>{selectedItems.map(i=><tr key={i.id}><Cell>{i.description}</Cell><Cell>{Number(i.quantity).toLocaleString()}</Cell>{selected.type==="request"?<><Cell>{i.unit}</Cell><Cell>{money(i.estimated_unit_cost)}</Cell><Cell>{money(i.estimated_total)}</Cell></>:<><Cell>{Number(i.received_quantity||0).toLocaleString()}</Cell><Cell>{money(i.unit_price)}</Cell><Cell>{money(i.discount_amount)}</Cell><Cell>{money(i.tax_amount)}</Cell><Cell>{money(i.line_total)}</Cell></>}</tr>)}</Table>
  {selected.type==="request"&&<section data-request-history style={{marginTop:18}}><h4>سجل دورة الطلب</h4><div style={{display:"grid",gap:8}}>{selectedHistory.map(entry=><div key={entry.id} style={{borderRight:"3px solid var(--color-border)",paddingRight:10}}><strong>{LABEL[entry.to_status]||entry.to_status}</strong><div><small>{new Date(entry.changed_at).toLocaleString("ar-SA")}{entry.from_status?` · من ${LABEL[entry.from_status]||entry.from_status}`:" · بداية السجل"}</small></div>{entry.reason&&<div>السبب: {entry.reason}</div>}</div>)}{!selectedHistory.length&&<small>لا يوجد سجل انتقالات متاح لهذا الطلب.</small>}</div></section>}
  {selected.type==="order"&&<><div style={gridStyle}><Info label="الإجمالي قبل الضريبة" value={money(selected.row.subtotal)}/><Info label="إجمالي الخصم" value={money(selected.row.discount_amount)}/><Info label="إجمالي الضريبة" value={money(selected.row.tax_amount)}/><Info label="الإجمالي النهائي" value={money(selected.row.total_amount)}/></div><h4>الاستلام والفواتير</h4><div style={{display:"grid",gap:6}}>{selectedReceipts.map(r=><div key={r.id} style={cardStyle}><span>{r.receipt_number} — {r.status}</span><small>{r.supplier_delivery_reference||"بدون مرجع تسليم"}</small></div>)}{selectedInvoices.map(i=><div key={i.id} style={cardStyle}><span>فاتورة {i.invoice_number} — {i.status}</span><strong>{money(i.total_amount)}</strong></div>)}{!selectedReceipts.length&&!selectedInvoices.length&&<small>لا يوجد استلام أو فاتورة مرتبطة حتى الآن.</small>}</div></>}
  {selected.type==="request"&&selected.row.status==="submitted"&&ws.capabilities.approve_request&&<div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:16}}><Button onClick={()=>setRejecting(selected.row)}>رفض بسبب</Button><Button onClick={()=>call("decide_purchase_request",{target_id:selected.row.id,approve:true,reason:null},"تم اعتماد الطلب بعد مراجعة التفاصيل.")}>اعتماد الطلب</Button></div>}
 </div></div>}
 {rejecting&&<div style={overlayStyle}><div style={{...modalStyle,width:"min(100%,520px)"}}><h3>رفض طلب الشراء</h3><Field label="سبب الرفض"><textarea style={{...inputStyle,width:"100%",minHeight:110}} value={rejectReason} onChange={e=>setRejectReason(e.target.value)} placeholder="اكتب سببًا واضحًا ليعرف مقدم الطلب المطلوب تعديله"/></Field><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:12}}><Button onClick={()=>{setRejecting(null);setRejectReason("")}}>رجوع</Button><Button onClick={()=>{if(!rejectReason.trim())return setError("سبب الرفض مطلوب.");void call("decide_purchase_request",{target_id:rejecting.id,approve:false,reason:rejectReason.trim()},"تم رفض الطلب مع تسجيل السبب.")}}>تأكيد الرفض</Button></div></div></div>}
 </div>;
}
