import React from "react";
export const money=(v)=>new Intl.NumberFormat("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
export const dateText=(v)=>v?new Date(v).toLocaleDateString("ar-EG"):"—";
export const inputStyle={border:"1px solid var(--color-border)",borderRadius:9,padding:"9px 10px",background:"var(--color-surface)",color:"var(--color-text)"};
export function friendlyError(error){const t=String(error?.message||error||"تعذر تنفيذ العملية");const m=[["Production access required","لا توجد صلاحية للوصول إلى أوامر الإنتاج."],["Production create access required","لا توجد صلاحية لإنشاء أمر إنتاج."],["Production planning access required","لا توجد صلاحية لتخطيط أمر الإنتاج."],["Production release access required","لا توجد صلاحية لإصدار أمر الإنتاج."],["Production material issue access required","لا توجد صلاحية لصرف خامات الإنتاج."],["Production operation access required","لا توجد صلاحية لتحديث خطوات الإنتاج."],["Production completion access required","لا توجد صلاحية لإكمال أمر الإنتاج."],["BOM material is not linked to an active inventory item","يوجد مكوّن في تركيبة المنتج غير مربوط بصنف مخزني نشط."],["Warehouse is required for product materials","اختر المخزن الذي ستُصرف منه خامات الأمر."],["Production order must be linked to a project","اربط أمر الإنتاج بمشروع قبل الإصدار."],["At least one material requirement is required","لا توجد خامات مطلوبة مرتبطة بأمر الإنتاج."],["Full required quantity must be issued exactly once","يجب صرف الكمية المطلوبة كاملة مرة واحدة."],["Insufficient inventory balance","الرصيد المتاح لا يكفي للصرف."]];for(const [n,l] of m)if(t.includes(n))return l;if(/constraint|violates|postgres|sqlstate|permission denied/i.test(t))return"تعذر تنفيذ العملية بسبب قيد في البيانات أو الصلاحيات. راجع المدخلات وحاول مرة أخرى.";return t;}
export function Panel({title,children,actions}){return <section style={{background:"var(--color-surface)",border:"1px solid var(--color-border)",borderRadius:14,padding:16,marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:12}}><strong>{title}</strong>{actions}</div>{children}</section>}
export function Button({children,onClick,disabled,tone="primary"}){return <button type="button" onClick={onClick} disabled={disabled} style={{border:0,borderRadius:9,padding:"9px 13px",cursor:disabled?"not-allowed":"pointer",fontWeight:700,background:tone==="danger"?"var(--color-danger)":tone==="ghost"?"var(--color-surface-muted)":"var(--color-wood)",color:tone==="ghost"?"var(--color-text)":"#fff",opacity:disabled?.55:1}}>{children}</button>}
export function Notice({type="info",children}){return <div style={{padding:12,borderRadius:10,marginBottom:12,background:type==="error"?"color-mix(in srgb,var(--color-danger) 12%,transparent)":"var(--color-surface-muted)",color:type==="error"?"var(--color-danger)":"var(--color-text)"}}>{children}</div>}
export function Field({label,children}){return <label style={{display:"grid",gap:6,fontSize:13,minWidth:170}}><span>{label}</span>{children}</label>}
