import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import{buildConfirmationUrl,CONFIRMATION_METHOD_LABELS,isPreviewConfirmationUrl,publicConfirmationBase}from"../src/assets/domain.js";

const migrationUrl=new URL("../supabase/migrations/202607180006_asset_confirmation_emergency_controls.sql",import.meta.url);
const appUrl=new URL("../src/assets/AssetsPage.jsx",import.meta.url);
const controlsUrl=new URL("../src/assets/EmergencyControls.jsx",import.meta.url);
const realtimeUrl=new URL("../src/realtime.js",import.meta.url);
const rootAppUrl=new URL("../src/AppMonolith.jsx",import.meta.url);
const docsUrl=new URL("../docs/ASSETS_TOOLS_FOUNDATION.md",import.meta.url);
const functionBody=(sql,name)=>sql.match(new RegExp(`create or replace function public\\.${name}\\([^]*?end \\$\\$;`,"i"))?.[0]||"";

test("confirmation trust methods never treat bearer links as verified identity",async()=>{const sql=await readFile(migrationUrl,"utf8"),ui=await readFile(appUrl,"utf8");for(const method of["authenticated_employee","otp","bearer_link","admin_override"])assert.match(sql,new RegExp(`'${method}'`));assert.match(functionBody(sql,"confirm_asset_assignment"),/apply_asset_assignment_confirmation_internal\(target_id,'bearer_link',null\)/);assert.match(functionBody(sql,"confirm_asset_return"),/apply_asset_return_confirmation_internal\(target_id,'bearer_link',null,null\)/);assert.match(sql,/'identity_verified',false/);assert.match(ui,/تأكيد عبر رابط غير موثّق بالهوية/);assert.equal(CONFIRMATION_METHOD_LABELS.bearer_link,"مؤكد عبر رابط غير موثّق بالهوية")});

test("authenticated employee confirmation records auth identity and enforces recipient linkage",async()=>{const sql=await readFile(migrationUrl,"utf8");for(const name of["confirm_asset_assignment_authenticated","confirm_asset_return_authenticated"]){const fn=functionBody(sql,name);assert.match(fn,/actor uuid:=auth\.uid\(\)/);assert.match(fn,/receiver_profile_id<>actor/);assert.match(fn,/status='active'/);assert.match(fn,/authenticated_employee',actor/)}assert.match(sql,/confirmed_by_user_id=actor/);assert.match(sql,/Confirmation audit fields are immutable/)});

test("all emergency RPCs are Owner-only, reasoned, locked and state-strict",async()=>{const sql=await readFile(migrationUrl,"utf8");const expectations={cancel_pending_asset_assignment:/status<>'pending_receiver_confirmation'/,force_confirm_asset_return:/status<>'pending_receiver_confirmation'/,cancel_pending_asset_return:/status<>'pending_receiver_confirmation'/,reverse_asset_assignment:/status<>'issued'/};for(const[name,stateGuard]of Object.entries(expectations)){const fn=functionBody(sql,name);assert.match(fn,/actor uuid:=auth\.uid\(\)/);assert.match(fn,/role='owner' and status='active'/);assert.match(fn,/btrim\(coalesce\(reason,''\)\)=''/);assert.match(fn,/for update/);assert.match(fn,stateGuard);assert.match(fn,/raise exception/)}assert.match(functionBody(sql,"force_confirm_asset_return"),/physical_receipt_verified is distinct from true/)});

test("emergency ledger effects compensate issues and never fake a cancelled return",async()=>{const sql=await readFile(migrationUrl,"utf8"),cancelIssue=functionBody(sql,"cancel_pending_asset_assignment"),reverse=functionBody(sql,"reverse_asset_assignment"),cancelReturn=functionBody(sql,"cancel_pending_asset_return"),forceReturn=functionBody(sql,"force_confirm_asset_return");for(const fn of[cancelIssue,reverse]){assert.match(fn,/movement_type,quantity,available_delta,assigned_delta/);assert.match(fn,/'reversed',item\.quantity,item\.quantity,-item\.quantity/);assert.match(fn,/'source','admin_override'/)}assert.doesNotMatch(cancelReturn,/insert into public\.asset_movements/);assert.match(cancelReturn,/'inventory_delta',0/);assert.match(cancelReturn,/'available_quantity_delta',0/);assert.match(forceReturn,/apply_asset_return_confirmation_internal\(target_id,'admin_override',actor/);assert.match(sql,/'forced_return_confirmation'/)});

test("completed or repeated emergency operations are safely rejected",async()=>{const sql=await readFile(migrationUrl,"utf8");assert.match(functionBody(sql,"cancel_pending_asset_assignment"),/Only a pending assignment can be cancelled/);assert.match(functionBody(sql,"cancel_pending_asset_return"),/Only an unconfirmed pending return can be cancelled/);assert.match(functionBody(sql,"force_confirm_asset_return"),/Only a pending physical return can be force-confirmed/);assert.match(functionBody(sql,"reverse_asset_assignment"),/Later returns or settlements make reversal inconsistent/)});

test("Realtime migration covers every asset table and uses a safe signal for private assets",async()=>{const sql=await readFile(migrationUrl,"utf8"),realtime=await readFile(realtimeUrl,"utf8"),app=await readFile(rootAppUrl,"utf8");for(const table of["asset_categories","asset_locations","asset_settings","assets","asset_assignments","asset_assignment_items","asset_return_events","asset_return_items","asset_settlements","asset_movements","asset_attachments","asset_realtime_signal"])assert.match(sql,new RegExp(`'${table}'`));assert.match(sql,/pg_publication_tables/);assert.match(sql,/asset_realtime_signal_read[\s\S]*has_permission\('assets_view'\)/);assert.match(realtime,/asset_realtime_signal:\s*"assetRealtimeSignal"/);assert.match(app,/key === "assetRealtimeSignal"[\s\S]*requestTableRefresh\("assets"\)/);assert.match(app,/await removeChannels\(\)/);assert.match(app,/supabase\.removeChannel/);assert.match(app,/setRealtimeStatus\("RECONNECTING"\)/);assert.match(app,/onClick=\{retryVisibleData\}/)});

test("configured production URL replaces preview origin and preview fallback is warned",()=>{const base=publicConfirmationBase("https://erp.nextep.example/app","https://branch-preview.vercel.app","/assets");assert.equal(new URL(base).hostname,"erp.nextep.example");assert.equal(new URL(buildConfirmationUrl(base,"id.secret","return")).searchParams.get("assetConfirmation"),"id.secret");assert.equal(isPreviewConfirmationUrl(base),false);assert.equal(isPreviewConfirmationUrl(publicConfirmationBase("","https://branch-preview.vercel.app","/")),true)});

test("UI exposes distinct Owner-only emergency actions and no fake OTP",async()=>{const app=await readFile(appUrl,"utf8"),controls=await readFile(controlsUrl,"utf8"),docs=await readFile(docsUrl,"utf8");assert.match(app,/profile\.role==="owner"/);for(const label of["إلغاء إصدار معلّق وإعادة الكمية","إلغاء طلب الإرجاع دون تعديل الرصيد","تأكيد استلام فعلي استثنائي","عكس عهدة صادرة وإعادة الرصيد"])assert.match(controls,new RegExp(label));assert.match(controls,/physicalVerified/);assert.match(controls,/سبب الإجراء الاستثنائي/);assert.match(docs,/OTP Provider مستقلًا/);assert.doesNotMatch(app,/otp[_ -]?(?:code|token)/i)});
