import test from"node:test";
import assert from"node:assert/strict";

const enabled=process.env.ASSETS_EMERGENCY_INTEGRATION==="1";
const required=["SUPABASE_TEST_URL","SUPABASE_TEST_ANON_KEY","SUPABASE_OWNER_ACCESS_TOKEN","SUPABASE_NON_OWNER_ACCESS_TOKEN","TEST_PENDING_ASSIGNMENT_ID","TEST_PENDING_RETURN_FORCE_ID","TEST_PENDING_RETURN_CANCEL_ID","TEST_ISSUED_ASSIGNMENT_ID"];
const missing=required.filter(key=>!process.env[key]);
const skipReason=!enabled?"set ASSETS_EMERGENCY_INTEGRATION=1 for a disposable Supabase fixture":missing.length?`missing ${missing.join(", ")}`:false;
async function call(name,token,args){const response=await fetch(`${process.env.SUPABASE_TEST_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:process.env.SUPABASE_TEST_ANON_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(args)});const body=await response.json().catch(()=>({}));return{response,body}}

test("disposable Supabase fixture enforces emergency authorization and transitions",{skip:skipReason},async()=>{const denied=await call("cancel_pending_asset_assignment",process.env.SUPABASE_NON_OWNER_ACCESS_TOKEN,{target_id:process.env.TEST_PENDING_ASSIGNMENT_ID,reason:"integration authorization check"});assert.equal(denied.response.ok,false);const cancelledIssue=await call("cancel_pending_asset_assignment",process.env.SUPABASE_OWNER_ACCESS_TOKEN,{target_id:process.env.TEST_PENDING_ASSIGNMENT_ID,reason:"integration pending issue cancellation"});assert.equal(cancelledIssue.response.ok,true);assert.equal(cancelledIssue.body.status,"reversed");const forced=await call("force_confirm_asset_return",process.env.SUPABASE_OWNER_ACCESS_TOKEN,{target_id:process.env.TEST_PENDING_RETURN_FORCE_ID,reason:"integration physical receipt",physical_receipt_verified:true});assert.equal(forced.response.ok,true);assert.equal(forced.body.confirmation_method,"admin_override");const cancelledReturn=await call("cancel_pending_asset_return",process.env.SUPABASE_OWNER_ACCESS_TOKEN,{target_id:process.env.TEST_PENDING_RETURN_CANCEL_ID,reason:"integration pending return cancellation"});assert.equal(cancelledReturn.response.ok,true);assert.equal(cancelledReturn.body.available_quantity_delta,0);const reversed=await call("reverse_asset_assignment",process.env.SUPABASE_OWNER_ACCESS_TOKEN,{target_id:process.env.TEST_ISSUED_ASSIGNMENT_ID,reason:"integration issued assignment reversal"});assert.equal(reversed.response.ok,true);assert.equal(reversed.body.status,"reversed")});
