import React,{useMemo,useState}from"react";
import{AlertTriangle,Archive,Check,Clipboard,ExternalLink,PackageCheck,Plus,QrCode,RotateCcw,Settings,Wrench}from"lucide-react";
import{supabase}from"../supabaseClient";
import{Button,DataTable,EmptyState,ErrorState,Field,Input,PageTitle,Panel,Select,StatCard,SuccessState,TextArea,money}from"../v22/shared";
import{confirmationStatusLabel,userFacingError}from"../userExperience";
import{ASSET_TYPES,ASSIGNMENT_STATUS,buildConfirmationUrl,CONFIRMATION_METHOD_LABELS,isPreviewConfirmationUrl,linkedProfileForEmployee,OPERATIONAL_STATUS,outstanding,publicConfirmationBase,whatsappMessage}from"./domain";
import{AssignmentEmergencyActions,ConfirmationBadge,EmergencyActionModal,EMERGENCY_ACTIONS,ReturnEmergencyActions}from"./EmergencyControls";
import"./assets.css";

const blankAsset=()=>({name:"",asset_type:"tool",category_id:"",tracking_mode:"serialized",quantity:1,unit:"قطعة",brand:"",model:"",serial_number:"",qr_value:"",barcode_value:"",purchase_date:"",purchase_cost:"",supplier_id:"",warranty_until:"",operational_status:"working",current_location_id:"",warehouse:"",shelf:"",notes:""});
async function rpc(name,args){const result=await supabase.rpc(name,args);console.info(`[Assets] ${name}`,result);if(result.error)throw new Error(userFacingError(result.error));if(result.data?.ok===false)throw new Error(userFacingError(result.data.error));return result.data}
export function AssetsPage({data,profile,permissions,refresh}){
 const [tab,setTab]=useState("overview"),[search,setSearch]=useState(new URLSearchParams(location.search).get("assetQr")||""),[type,setType]=useState(""),[status,setStatus]=useState("");
 const [assetForm,setAssetForm]=useState(null),[issueForm,setIssueForm]=useState(null),[returnForm,setReturnForm]=useState(null),[settlementForm,setSettlementForm]=useState(null),[categoryName,setCategoryName]=useState(""),[locationForm,setLocationForm]=useState({name:"",location_type:"factory"});
 const [file,setFile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[share,setShare]=useState(null),[emergency,setEmergency]=useState(null);
 const assets=(data.assets||[]).filter(a=>(!search||`${a.name} ${a.asset_code} ${a.serial_number||""} ${a.qr_value||""}`.toLowerCase().includes(search.toLowerCase()))&&(!type||a.asset_type===type)&&(!status||a.operational_status===status));
 const activeAssignments=(data.assetAssignments||[]).filter(a=>["pending_receiver_confirmation","issued","partially_returned","settlement_pending"].includes(a.status));
 const alerts=data.assetAlerts||[];
 async function reload(){await Promise.all(["assets","assetCategories","assetLocations","assetAssignments","assetAssignmentItems","assetReturnEvents","assetReturnItems","assetSettlements","assetMovements","assetAlerts"].map(refresh))}
 async function createAsset(e){e.preventDefault();setBusy(true);setError("");try{const result=await rpc("create_asset",{payload:assetForm});if(file){const path=`${result.asset.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const upload=await supabase.storage.from("asset-attachments").upload(path,file);if(upload.error)throw upload.error;const meta=await supabase.from("asset_attachments").insert({asset_id:result.asset.id,file_name:file.name,file_path:path,file_type:file.type,file_size:file.size});if(meta.error)throw meta.error}await reload();setAssetForm(null);setFile(null);setSuccess("تم تسجيل الأصل وإنشاء حركة الرصيد الافتتاحية.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function issue(e){e.preventDefault();setBusy(true);try{const linkedProfile=linkedProfileForEmployee(data.profiles,issueForm.receiver_employee_id);const result=await rpc("issue_asset_assignment",{payload:{...issueForm,receiver_profile_id:linkedProfile?.id||null,items:[{asset_id:issueForm.asset_id,quantity:Number(issueForm.quantity)}]}});await reload();const base=publicConfirmationBase(import.meta.env.VITE_PUBLIC_APP_URL,location.origin,location.pathname),url=buildConfirmationUrl(base,result.confirmation_token,"issue");const ass=(data.assetAssignments||[]).find(a=>a.id===result.assignment_id);setShare({url,message:whatsappMessage({code:result.assignment_code,url}),phone:ass?.receiver_phone_snapshot,previewWarning:isPreviewConfirmationUrl(base)});setIssueForm(null);setSuccess(linkedProfile?"تم إصدار العهدة، ويلزم تأكيدها بحساب الموظف المرتبط.":"تم إصدار العهدة عبر رابط غير موثّق بالهوية لعدم وجود حساب مرتبط.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function createReturn(e){e.preventDefault();setBusy(true);try{const result=await rpc("create_asset_return",{payload:{assignment_id:returnForm.assignment_id,items:[{assignment_item_id:returnForm.assignment_item_id,quantity:Number(returnForm.quantity),condition_at_return:returnForm.condition_at_return,shortage_quantity:0}],notes:returnForm.notes}});await reload();const ass=data.assetAssignments.find(a=>a.id===returnForm.assignment_id),base=publicConfirmationBase(import.meta.env.VITE_PUBLIC_APP_URL,location.origin,location.pathname),url=buildConfirmationUrl(base,result.confirmation_token,"return");setShare({url,message:whatsappMessage({code:ass?.assignment_code,url,kind:"return"}),phone:ass?.receiver_phone_snapshot,previewWarning:isPreviewConfirmationUrl(base)});setReturnForm(null);setSuccess("تم تسجيل الإرجاع وهو بانتظار التأكيد.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function executeEmergency(action){const config=EMERGENCY_ACTIONS[action.type];setBusy(true);setError("");try{const args={target_id:action.targetId,reason:action.reason};if(action.type==="force_confirm_return")args.physical_receipt_verified=action.physicalVerified;await rpc(config.rpc,args);await reload();setEmergency(null);setSuccess(config.success)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function renewLink(targetId,kind,assignment){setBusy(true);setError("");try{const result=await rpc("renew_asset_confirmation_link",{target_id:targetId,target_kind:kind});if(result.status!=="valid")throw new Error(result.status==="already_confirmed"?"تم تأكيد العملية بالفعل.":"لا يمكن إنشاء رابط لهذه الحالة.");await reload();const base=publicConfirmationBase(import.meta.env.VITE_PUBLIC_APP_URL,location.origin,location.pathname),url=buildConfirmationUrl(base,result.confirmation_token,kind);setShare({url,message:whatsappMessage({code:assignment?.assignment_code||result.assignment_code,url,kind}),phone:assignment?.receiver_phone_snapshot,previewWarning:isPreviewConfirmationUrl(base)});setSuccess("تم إنشاء رابط تأكيد جديد وتسجيل إعادة الإرسال.")}catch(e){setError(userFacingError(e))}finally{setBusy(false)}}
 async function createSettlement(e){e.preventDefault();setBusy(true);try{await rpc("create_asset_settlement",{payload:{...settlementForm,quantity:Number(settlementForm.quantity),estimated_loss:settlementForm.estimated_loss}});await reload();setSettlementForm(null);setSuccess("تم إرسال التسوية للاعتماد.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function decideSettlement(id,approve){setBusy(true);try{await rpc("approve_asset_settlement",{target_id:id,approve,decision_notes:null});await reload();setSuccess(approve?"تم اعتماد التسوية وتسجيل حركة الخسارة.":"تم رفض التسوية.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveCategory(e){e.preventDefault();setBusy(true);try{await rpc("save_asset_category",{target_id:null,name_value:categoryName,active_value:true});await refresh("assetCategories");setCategoryName("");setSuccess("تمت إضافة التصنيف.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveLocation(e){e.preventDefault();setBusy(true);try{await rpc("save_asset_location",{payload:locationForm});await refresh("assetLocations");setLocationForm({name:"",location_type:"factory"});setSuccess("تمت إضافة الموقع.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 const stats=useMemo(()=>({total:(data.assets||[]).length,available:(data.assets||[]).filter(a=>Number(a.available_quantity)>0).length,active:activeAssignments.length,risk:(data.assets||[]).filter(a=>["lost","stolen","damaged","under_maintenance"].includes(a.operational_status)).length}),[data.assets,activeAssignments.length]);
 const tabs=[['overview','نظرة عامة'],['registry','سجل الأصول'],['assignments','العهد النشطة'],['returns','الإرجاعات'],['maintenance','الصيانة'],['alerts','التنبيهات'],['reports','التقارير'],['settings','الإعدادات']];
 return <div className="assets-page"><PageTitle eyebrow="Assets & Tools Management" title="الأصول والعِدّة" description="سجل موحد للأصول والعهد والإرجاعات بحركة غير قابلة للتعديل." actions={<>{permissions.assets_manage&&<Button onClick={()=>setAssetForm(blankAsset())}><Plus size={16}/> أصل جديد</Button>}{permissions.assets_issue&&<Button onClick={()=>setIssueForm({receiver_employee_id:"",receiver_profile_id:"",asset_id:"",quantity:1,purpose:"",project_id:"",department_id:"",issue_location_id:"",expected_return_at:"",notes:""})}><PackageCheck size={16}/> إصدار عهدة</Button>}</>}/><ErrorState error={error}/><SuccessState message={success}/>
 <div className="asset-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="overview"&&<><div className="v22-grid cols-4"><StatCard label="إجمالي السجلات" value={stats.total}/><StatCard label="متاح للإصدار" value={stats.available} tone="positive"/><StatCard label="عهد نشطة" value={stats.active}/><StatCard label="مخاطر وصيانة" value={stats.risk} tone="negative"/></div><Panel><h3>التنبيهات الحالية</h3>{alerts.length?<AlertList alerts={alerts}/>:<EmptyState title="لا توجد تنبيهات حرجة" description="الأصول والعهد ضمن الحدود المحددة."/>}</Panel></>}
 {tab==="registry"&&<Panel><div className="v22-filters"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم أو الكود أو التسلسل أو QR"/><Select value={type} onChange={e=>setType(e.target.value)}><option value="">كل الأنواع</option>{Object.entries(ASSET_TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(OPERATIONAL_STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></div>{assets.length?<DataTable headers={["الكود","الأصل","النوع","الرصيد المتاح","الحالة","الموقع","QR"]}>{assets.map(a=><tr key={a.id}><td><b>{a.asset_code}</b></td><td>{a.name}<small className="table-sub">{a.serial_number||a.brand||"—"}</small></td><td>{ASSET_TYPES[a.asset_type]}</td><td>{a.available_quantity} / {a.total_quantity} {a.unit}</td><td><span className={`asset-status ${a.operational_status}`}>{OPERATIONAL_STATUS[a.operational_status]}</span></td><td>{data.assetLocations?.find(l=>l.id===a.current_location_id)?.name||"—"}</td><td><QrCode size={18}/><small className="table-sub">{a.qr_value}</small></td></tr>)}</DataTable>:<EmptyState title="لا توجد أصول مطابقة"/>}</Panel>}
 {tab==="assignments"&&<Panel>{activeAssignments.length?<DataTable headers={["العهدة","المستلم","المشروع","الحالة والثقة","موعد الإرجاع","المتبقي","الإجراءات"]}>{activeAssignments.map(a=>{const items=data.assetAssignmentItems.filter(i=>i.assignment_id===a.id),quantity=items.reduce((s,i)=>s+outstanding(i),0);return <tr key={a.id}><td><b>{a.assignment_code}</b></td><td>{a.receiver_name_snapshot}</td><td>{data.projects.find(p=>p.id===a.project_id)?.project_name||"—"}</td><td>{ASSIGNMENT_STATUS[a.status]}<ConfirmationBadge method={a.confirmation_method}/><small className="table-sub">الرابط: {confirmationStatusLabel(a)}</small><small className="table-sub">الرابط: {confirmationStatusLabel(a)}</small></td><td>{a.expected_return_at?new Date(a.expected_return_at).toLocaleString("ar-SA"):"—"}</td><td>{quantity}</td><td><div className="asset-row-actions">{permissions.assets_return&&a.status==="issued"&&<Button variant="ghost" onClick={()=>setReturnForm({assignment_id:a.id,assignment_item_id:items.find(i=>outstanding(i)>0)?.id||"",quantity:1,condition_at_return:"working",notes:""})}><RotateCcw size={14}/> تسجيل إرجاع</Button>}{a.status==="pending_receiver_confirmation"&&permissions.assets_issue&&<Button variant="ghost" onClick={()=>renewLink(a.id,"issue",a)}><ExternalLink size={14}/> إرسال/إعادة إرسال الرابط</Button>}{a.status==="pending_receiver_confirmation"&&permissions.assets_issue&&<Button variant="ghost" onClick={()=>renewLink(a.id,"issue",a)}><ExternalLink size={14}/> إرسال/إعادة إرسال الرابط</Button>}{profile.role==="owner"&&<AssignmentEmergencyActions assignment={a} quantity={quantity} onSelect={setEmergency}/>}</div></td></tr>})}</DataTable>:<EmptyState title="لا توجد عهد نشطة"/>}</Panel>}
 {tab==="returns"&&<Panel>{data.assetReturnEvents.length?<DataTable headers={["العهدة","وقت الاستلام","الحالة والثقة","استلمها","إجراءات Owner"]}>{data.assetReturnEvents.map(r=>{const quantity=data.assetReturnItems.filter(i=>i.return_event_id===r.id).reduce((sum,item)=>sum+Number(item.quantity||0),0);return <tr key={r.id}><td>{data.assetAssignments.find(a=>a.id===r.assignment_id)?.assignment_code}</td><td>{new Date(r.received_at).toLocaleString("ar-SA")}</td><td>{r.status}<ConfirmationBadge method={r.confirmation_method}/><small className="table-sub">الرابط: {confirmationStatusLabel(r)}</small></td><td>{data.profiles.find(p=>p.id===r.received_by)?.full_name||"النظام"}</td><td><div className="asset-row-actions">{r.status==="pending_receiver_confirmation"&&permissions.assets_return&&<Button variant="ghost" onClick={()=>renewLink(r.id,"return",data.assetAssignments.find(a=>a.id===r.assignment_id))}><ExternalLink size={14}/> إرسال/إعادة إرسال الرابط</Button>}{profile.role==="owner"&&<ReturnEmergencyActions event={r} quantity={quantity} onSelect={setEmergency}/>}</div></td></tr>})}</DataTable>:<EmptyState title="لا توجد إرجاعات"/>}</Panel>}
 {tab==="maintenance"&&<Panel>{data.assets.filter(a=>["needs_maintenance","under_maintenance","damaged"].includes(a.operational_status)).length?<AssetRiskRows assets={data.assets}/>:<EmptyState title="لا توجد أصول تحتاج صيانة" description="الصيانة المتقدمة مؤجلة، وتعرض هذه المرحلة الحالات الأساسية فقط."/>}</Panel>}
 {tab==="alerts"&&<Panel>{alerts.length?<AlertList alerts={alerts}/>:<EmptyState title="لا توجد تنبيهات"/>}</Panel>}
 {tab==="reports"&&<Panel><div className="v22-grid cols-4"><StatCard label="القيمة المسجلة" value={permissions.assets_reports?money(data.assets.reduce((s,a)=>s+Number(a.purchase_cost||0),0)):"محجوبة"}/><StatCard label="الكمية المعينة" value={data.assets.reduce((s,a)=>s+Number(a.assigned_quantity||0),0)}/><StatCard label="مفقود أو مسروق" value={data.assets.filter(a=>["lost","stolen"].includes(a.operational_status)).length}/><StatCard label="حركات Ledger" value={data.assetMovements.length}/></div></Panel>}
 {tab==="settings"&&<SettingsTab data={data} permissions={permissions} categoryName={categoryName} setCategoryName={setCategoryName} saveCategory={saveCategory} locationForm={locationForm} setLocationForm={setLocationForm} saveLocation={saveLocation}/>} 
 {assetForm&&<AssetModal form={assetForm} setForm={setAssetForm} data={data} file={file} setFile={setFile} busy={busy} onSubmit={createAsset} onClose={()=>setAssetForm(null)}/>}
 {issueForm&&<IssueModal form={issueForm} setForm={setIssueForm} data={data} busy={busy} onSubmit={issue} onClose={()=>setIssueForm(null)}/>}
 {returnForm&&<ReturnModal form={returnForm} setForm={setReturnForm} data={data} busy={busy} onSubmit={createReturn} onClose={()=>setReturnForm(null)} onSettle={permissions.assets_adjust?()=>{setSettlementForm({assignment_item_id:returnForm.assignment_item_id,settlement_type:"lost",quantity:returnForm.quantity,reason:"",notes:"",estimated_loss:""});setReturnForm(null)}:null}/>}
 {settlementForm&&<SettlementModal form={settlementForm} setForm={setSettlementForm} busy={busy} onSubmit={createSettlement} onClose={()=>setSettlementForm(null)}/>}
 {share&&<ShareDialog share={share} onClose={()=>setShare(null)}/>}
 {emergency&&<EmergencyActionModal action={emergency} busy={busy} onConfirm={executeEmergency} onClose={()=>setEmergency(null)}/>}
 {permissions.assets_approve_loss&&data.assetSettlements.filter(s=>s.status==="pending_approval").map(s=><Panel key={s.id} className="settlement-review"><AlertTriangle/><div><b>تسوية {s.settlement_type}</b><span>{s.quantity} · {s.reason}</span></div><Button disabled={busy||profile.role==="accountant"&&s.created_by===profile.id} onClick={()=>decideSettlement(s.id,true)}><Check size={14}/> اعتماد</Button><Button variant="danger" onClick={()=>decideSettlement(s.id,false)}>رفض</Button></Panel>)}
 </div>
}
function AssetModal({form,setForm,data,file,setFile,busy,onSubmit,onClose}){return <Modal title="تسجيل أصل" onSubmit={onSubmit} onClose={onClose} busy={busy}><Field label="الاسم"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="النوع"><Select value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value})}>{Object.entries(ASSET_TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="التصنيف"><Select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">اختر</option>{data.assetCategories.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="طريقة التتبع"><Select value={form.tracking_mode} onChange={e=>setForm({...form,tracking_mode:e.target.value,quantity:e.target.value==="serialized"?1:form.quantity})}><option value="serialized">قطعة فردية</option><option value="quantity">أصل كمي</option></Select></Field><Field label="الكمية"><Input type="number" min="1" step=".001" disabled={form.tracking_mode==="serialized"} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="الوحدة"><Input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></Field><Field label="الماركة"><Input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></Field><Field label="الموديل"><Input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></Field><Field label="الرقم التسلسلي"><Input value={form.serial_number} onChange={e=>setForm({...form,serial_number:e.target.value})}/></Field><Field label="QR مخصص"><Input value={form.qr_value} placeholder="يولد تلقائيًا عند تركه فارغًا" onChange={e=>setForm({...form,qr_value:e.target.value})}/></Field><Field label="الموقع"><Select value={form.current_location_id} onChange={e=>setForm({...form,current_location_id:e.target.value})}><option value="">غير محدد</option>{data.assetLocations.filter(l=>l.is_active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select></Field><Field label="تكلفة الشراء"><Input type="number" min="0" value={form.purchase_cost} onChange={e=>setForm({...form,purchase_cost:e.target.value})}/></Field><Field label="صورة أو PDF"><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="ملاحظات" wide><TextArea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></Modal>}
function IssueModal({form,setForm,data,busy,onSubmit,onClose}){const asset=data.assets.find(a=>a.id===form.asset_id),employee=data.employees.find(e=>e.id===form.receiver_employee_id),linkedProfile=linkedProfileForEmployee(data.profiles,form.receiver_employee_id);return <Modal title="إصدار عهدة" onSubmit={onSubmit} onClose={onClose} busy={busy}><Field label="المستلم"><Select required value={form.receiver_employee_id} onChange={e=>{const employeeId=e.target.value,profile=linkedProfileForEmployee(data.profiles,employeeId);setForm({...form,receiver_employee_id:employeeId,receiver_profile_id:profile?.id||""})}}><option value="">اختر</option>{data.employees.filter(e=>e.status==="active").map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</Select></Field><Field label="هوية التأكيد"><div className={`linked-account-summary ${linkedProfile?"verified":"unlinked"}`}><strong>{employee?employee.full_name:"اختر الموظف أولًا"}</strong>{employee&&(linkedProfile?<span>الحساب المرتبط: {linkedProfile.full_name||linkedProfile.email} — التأكيد بحساب الموظف</span>:<span>لا يوجد حساب نظام مرتبط — التأكيد عبر الرابط غير موثّق بالهوية</span>)}</div></Field><Field label="الأصل"><Select required value={form.asset_id} onChange={e=>setForm({...form,asset_id:e.target.value,quantity:1})}><option value="">اختر</option>{data.assets.filter(a=>a.operational_status==="working"&&Number(a.available_quantity)>0).map(a=><option key={a.id} value={a.id}>{a.asset_code} · {a.name} ({a.available_quantity})</option>)}</Select></Field><Field label="الكمية"><Input required type="number" min="1" max={asset?.available_quantity||1} step=".001" disabled={asset?.tracking_mode==="serialized"} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="المشروع"><Select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">بدون مشروع</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.project_name}</option>)}</Select></Field><Field label="سبب الاستخدام"><Input required value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></Field><Field label="متوقع الرجوع"><Input type="datetime-local" value={form.expected_return_at} onChange={e=>setForm({...form,expected_return_at:e.target.value})}/></Field></Modal>}
function ReturnModal({form,setForm,data,busy,onSubmit,onClose,onSettle}){const items=data.assetAssignmentItems.filter(i=>i.assignment_id===form.assignment_id&&outstanding(i)>0);return <Modal title="تسجيل إرجاع" onSubmit={onSubmit} onClose={onClose} busy={busy} extra={onSettle&&<Button type="button" variant="danger" onClick={onSettle}>تسجيل فقد أو تلف</Button>}><Field label="البند"><Select required value={form.assignment_item_id} onChange={e=>setForm({...form,assignment_item_id:e.target.value})}>{items.map(i=><option key={i.id} value={i.id}>{data.assets.find(a=>a.id===i.asset_id)?.name} · متبقي {outstanding(i)}</option>)}</Select></Field><Field label="الكمية"><Input required type="number" min=".001" max={outstanding(items.find(i=>i.id===form.assignment_item_id))} step=".001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="الحالة عند الرجوع"><Select value={form.condition_at_return} onChange={e=>setForm({...form,condition_at_return:e.target.value})}><option value="working">سليم</option><option value="needs_maintenance">يحتاج صيانة</option><option value="damaged">تالف</option></Select></Field><Field label="ملاحظات" wide><TextArea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></Modal>}
function SettlementModal({form,setForm,busy,onSubmit,onClose}){return <Modal title="تسوية فقد أو تلف" onSubmit={onSubmit} onClose={onClose} busy={busy}><Field label="النوع"><Select value={form.settlement_type} onChange={e=>setForm({...form,settlement_type:e.target.value})}><option value="lost">مفقود</option><option value="stolen">مسروق</option><option value="damaged">تالف</option><option value="not_returned">لم يعد</option><option value="written_off">شطب</option></Select></Field><Field label="الكمية"><Input type="number" min=".001" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="الخسارة التقديرية"><Input type="number" min="0" value={form.estimated_loss} onChange={e=>setForm({...form,estimated_loss:e.target.value})}/></Field><Field label="السبب"><TextArea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field></Modal>}
function Modal({title,children,onSubmit,onClose,busy,extra}){return <div className="v22-modal-backdrop"><form className="v22-modal asset-modal" onSubmit={onSubmit}><h3>{title}</h3><div className="v22-form-grid">{children}</div><div className="v22-actions">{extra}<Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button disabled={busy}>حفظ</Button></div></form></div>}
function ShareDialog({share,onClose}){async function copy(){await navigator.clipboard.writeText(share.message)}return <div className="v22-modal-backdrop"><div className="v22-modal"><h3>رابط التأكيد جاهز</h3><p className="bearer-trust-warning">تأكيد عبر رابط غير موثّق بالهوية — امتلاك الرابط لا يثبت أن صاحبه هو الموظف المستلم.</p>{share.previewWarning&&<p className="preview-link-warning"><AlertTriangle size={16}/> هذا رابط Development/Preview وقد تمنع Vercel Deployment Protection المستلم من فتحه. اضبط VITE_PUBLIC_APP_URL على نطاق الإنتاج العام.</p>}<div className="share-message">{share.message}</div><div className="v22-actions"><Button variant="ghost" onClick={copy}><Clipboard size={15}/> نسخ رسالة واتساب</Button><a className="v22-button primary" href={`https://wa.me/${(share.phone||"").replace(/\D/g,"")}?text=${encodeURIComponent(share.message)}`} target="_blank" rel="noreferrer"><ExternalLink size={15}/> فتح واتساب</a><Button onClick={onClose}>تم</Button></div></div></div>}
function SettingsTab({data,permissions,categoryName,setCategoryName,saveCategory,locationForm,setLocationForm,saveLocation}){if(!permissions.assets_manage)return <Panel><EmptyState title="لا تملك صلاحية الإعدادات"/></Panel>;return <div className="settings-grid"><Panel><h3><Settings size={17}/> التصنيفات</h3><form className="inline-form" onSubmit={saveCategory}><Input required value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="تصنيف جديد"/><Button>إضافة</Button></form>{data.assetCategories.map(c=><div className="setting-row" key={c.id}><span>{c.name}</span><small>{c.is_active?"فعال":"معطل"}</small></div>)}</Panel><Panel><h3>المواقع</h3><form className="inline-form" onSubmit={saveLocation}><Input required value={locationForm.name} onChange={e=>setLocationForm({...locationForm,name:e.target.value})} placeholder="اسم الموقع"/><Select value={locationForm.location_type} onChange={e=>setLocationForm({...locationForm,location_type:e.target.value})}><option value="factory">مصنع</option><option value="warehouse">مخزن</option><option value="shelf">رف</option><option value="external">خارجي</option><option value="quarantine">عزل</option></Select><Button>إضافة</Button></form>{data.assetLocations.map(l=><div className="setting-row" key={l.id}><span>{l.name}</span><small>{l.location_type}</small></div>)}</Panel></div>}
function AlertList({alerts}){return <div className="asset-alerts">{alerts.map((a,i)=><div key={`${a.alert_type}-${a.reference_id}-${i}`}><AlertTriangle size={17}/><span><b>{a.title}</b>{a.alert_type}</span><small>{a.due_at?new Date(a.due_at).toLocaleString("ar-SA"):""}</small></div>)}</div>}
function AssetRiskRows({assets}){const rows=assets.filter(a=>["needs_maintenance","under_maintenance","damaged"].includes(a.operational_status));return <DataTable headers={["الكود","الأصل","الحالة"]}>{rows.map(a=><tr key={a.id}><td>{a.asset_code}</td><td>{a.name}</td><td>{OPERATIONAL_STATUS[a.operational_status]}</td></tr>)}</DataTable>}

export function AssetExternalConfirmation(){
 const params=new URLSearchParams(location.search),raw=params.get("assetConfirmation")||"",kind=params.get("kind")||"issue",[id,secret]=raw.split(".");
 const [state,setState]=useState({status:"loading"});
 async function load(){if(!id||!secret)return setState({status:"not_found"});await supabase.auth.getSession();const result=await supabase.rpc(kind==="return"?"asset_return_confirmation_preview":"asset_confirmation_preview",{target_id:id,secret});setState(result.error?{status:"not_found"}:result.data)}
 React.useEffect(()=>{load()},[]);
 async function confirm(){const authenticated=state.authenticated_confirmation_available,rpcName=authenticated?(kind==="return"?"confirm_asset_return_authenticated":"confirm_asset_assignment_authenticated"):(kind==="return"?"confirm_asset_return":"confirm_asset_assignment"),args=authenticated?{target_id:id}:{target_id:id,secret};const result=await supabase.rpc(rpcName,args);setState(result.error?{status:"expired"}:result.data)}
 if(state.status==="authentication_required")return <ExternalState title="يلزم تسجيل دخول الموظف المرتبط" text="هذه العهدة مرتبطة بحساب نظام محدد، ولا يمكن اعتمادها كرابط حيازة غير موثّق."/>;
 const linkMessages={not_found:["الرابط غير صحيح","تعذر العثور على عملية مرتبطة بهذا الرابط."],invalid:["الرابط غير صحيح","رمز التأكيد غير صحيح."],expired:["انتهت صلاحية الرابط","انتهت مدة التأكيد وما زالت العملية معلقة. اطلب رابطًا جديدًا."],rate_limited:["تم إيقاف المحاولات مؤقتًا","تم تجاوز عدد المحاولات. حاول لاحقًا."],already_confirmed:["تم التأكيد مسبقًا","هذه العملية مكتملة بالفعل."],already_used:["تم استخدام الرابط","تم استخدام هذا الرابط من قبل."],cancelled:["تم إلغاء العملية","لا يمكن استخدام رابط تابع لعملية ملغاة."],replaced:["تم استبدال الرابط","استخدم آخر رابط تم إرساله."],pending_without_link:["لا يوجد رابط نشط","العملية معلقة لكن لم يتم إنشاء رابط لها."],not_pending:["تغيرت حالة العملية","حدّث الصفحة لمعرفة الحالة الحالية."]};if(linkMessages[state.status])return <ExternalState title={linkMessages[state.status][0]} text={linkMessages[state.status][1]}/>;
 if(state.status==="confirmed")return <ExternalState title="تم التأكيد بنجاح" text={`${CONFIRMATION_METHOD_LABELS[state.confirmation_method]||"تم تسجيل طريقة التأكيد"}. يمكن إغلاق الصفحة الآن.`} success/>;
 if(state.status==="loading")return <ExternalState title="جارِ التحقق من الرابط" text="لحظات من فضلك…"/>;
 return <main className="asset-confirm-page"><div className="asset-confirm-card"><Archive size={34}/><h1>{kind==="return"?"تأكيد إرجاع العهدة":"تأكيد استلام العهدة"}</h1><p>رقم العهدة: <b>{state.assignment_code||"محمي"}</b></p>{state.receiver_name&&<p>المستلم: {state.receiver_name}</p>}{state.receiver_phone&&<p>الهاتف: {state.receiver_phone}</p>}<p className={state.authenticated_confirmation_available?"authenticated-trust":"bearer-trust-warning"}>{state.authenticated_confirmation_available?"سيُسجل التأكيد بحساب الموظف المسجل الدخول حاليًا.":"تأكيد عبر رابط غير موثّق بالهوية — الرابط يثبت حيازته فقط ولا يثبت هوية الموظف."}</p><div className="confirm-items">{state.items?.map((i,n)=><div key={n}><span>{i.name}</span><b>{i.quantity} {i.unit}</b></div>)}</div><Button onClick={confirm}><Check size={16}/> {state.authenticated_confirmation_available?"تأكيد بحساب الموظف":"تأكيد عبر الرابط"}</Button><small>هذه الصفحة مخصصة للتأكيد فقط ولا تتيح التنقل داخل النظام.</small></div></main>
}
function ExternalState({title,text,success}) {return <main className="asset-confirm-page"><div className={`asset-confirm-card ${success?"success":""}`}><Archive size={34}/><h1>{title}</h1><p>{text}</p></div></main>}
