import React, { useMemo, useState } from "react";
import { Banknote, Clock3, Plus, Trash2 } from "lucide-react";
import { supabase } from "../supabaseClient";
import { Button, ConfirmDialog, DataTable, EmptyState, ErrorState, Field, Input, money, number, PageTitle, Panel, PermissionGuard, Select, StatCard, TextArea, today } from "./shared";
import { calculateDailyLabor } from "./calculations";

const emptyShift = { worker_name:"", phone:"", trade:"", project_id:"", work_date:today(), start_time:"08:00", end_time:"17:00", break_minutes:60, hourly_rate:0, overtime_hours:0, overtime_rate:0, payment_status:"unpaid", notes:"" };
const PAYMENT_STATUS = { unpaid:"غير مدفوع", partially_paid:"مدفوع جزئيًا", paid:"مدفوع" };

export function DailyLaborForm({ projects, profile, canSeeMoney, onSaved, onCancel }) {
  const [form,setForm]=useState(emptyShift); const [error,setError]=useState(""); const calculation=calculateDailyLabor(form);
  async function submit(e){e.preventDefault();setError("");const payload={...form,project_id:form.project_id||null,break_minutes:number(form.break_minutes),hourly_rate:canSeeMoney?number(form.hourly_rate):0,overtime_hours:number(form.overtime_hours),overtime_rate:canSeeMoney?number(form.overtime_rate):0,total_hours:calculation.totalHours,total_amount:calculation.totalAmount,created_by:profile.id};const{error:err}=await supabase.from("daily_labor").insert(payload);if(err)return setError(err.message);onSaved()}
  return <form onSubmit={submit}><div className="v22-form-grid"><Field label="اسم العامل"><Input required value={form.worker_name} onChange={(e)=>setForm({...form,worker_name:e.target.value})}/></Field><Field label="الهاتف"><Input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></Field><Field label="الحرفة"><Input value={form.trade} onChange={(e)=>setForm({...form,trade:e.target.value})}/></Field><Field label="المشروع"><Select value={form.project_id} onChange={(e)=>setForm({...form,project_id:e.target.value})}><option value="">بدون مشروع</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.project_code} · {p.project_name}</option>)}</Select></Field><Field label="تاريخ العمل"><Input required type="date" value={form.work_date} onChange={(e)=>setForm({...form,work_date:e.target.value})}/></Field><Field label="بداية الوردية"><Input required type="time" value={form.start_time} onChange={(e)=>setForm({...form,start_time:e.target.value})}/></Field><Field label="نهاية الوردية"><Input required type="time" value={form.end_time} onChange={(e)=>setForm({...form,end_time:e.target.value})}/></Field><Field label="الراحة بالدقائق"><Input type="number" min="0" value={form.break_minutes} onChange={(e)=>setForm({...form,break_minutes:e.target.value})}/></Field><PermissionGuard allow={canSeeMoney}><Field label="سعر الساعة"><Input type="number" min="0" value={form.hourly_rate} onChange={(e)=>setForm({...form,hourly_rate:e.target.value})}/></Field><Field label="سعر الساعة الإضافية"><Input type="number" min="0" value={form.overtime_rate} onChange={(e)=>setForm({...form,overtime_rate:e.target.value})}/></Field></PermissionGuard><Field label="ساعات إضافية"><Input type="number" min="0" step=".25" value={form.overtime_hours} onChange={(e)=>setForm({...form,overtime_hours:e.target.value})}/></Field><Field label="ملاحظات" wide><TextArea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field></div><div className="labor-calculation"><span><Clock3 size={15}/> إجمالي الساعات <b>{calculation.totalHours}</b></span>{canSeeMoney&&<span>القيمة المستحقة <b>{money(calculation.totalAmount)}</b></span>}</div><ErrorState error={error}/><div className="v22-actions modal-actions"><Button type="button" variant="ghost" onClick={onCancel}>إلغاء</Button><Button>حفظ الوردية</Button></div></form>;
}

export function DailyLaborTab({ data, profile, permissions, refresh }) {
  const [showForm,setShowForm]=useState(false);const [from,setFrom]=useState("");const [to,setTo]=useState("");const [project,setProject]=useState("");const [group,setGroup]=useState("none");const [error,setError]=useState("");const [pendingPaid,setPendingPaid]=useState(null);const canSeeMoney=profile.role!=="production";
  const rows=useMemo(()=>data.dailyLabor.filter((r)=>(!from||r.work_date>=from)&&(!to||r.work_date<=to)&&(!project||r.project_id===project)).sort((a,b)=>b.work_date.localeCompare(a.work_date)),[data.dailyLabor,from,to,project]);
  const summary=useMemo(()=>rows.reduce((a,r)=>({hours:a.hours+number(r.total_hours),total:a.total+number(r.total_amount),paid:a.paid+number(r.paid_amount),unpaid:a.unpaid+Math.max(0,number(r.total_amount)-number(r.paid_amount))}),{hours:0,total:0,paid:0,unpaid:0}),[rows]);
  const grouped=useMemo(()=>group==="none"?[["كل الورديات",rows]]:Object.entries(rows.reduce((a,r)=>{const key=group==="worker"?r.worker_name:(data.projects.find((p)=>p.id===r.project_id)?.project_name||"بدون مشروع");(a[key]??=[]).push(r);return a},{})),[rows,group,data.projects]);
  async function markPaid(row){setError("");const{error:err}=await supabase.from("daily_labor").update({payment_status:"paid",paid_amount:row.total_amount}).eq("id",row.id);if(err)return setError(err.message);await refresh("dailyLabor")}
  async function remove(row){const{error:err}=await supabase.from("daily_labor").delete().eq("id",row.id);if(err)return setError(err.message);refresh("dailyLabor")}
  return <div><PageTitle eyebrow="تكلفة العمل المؤقت" title="العمالة اليومية" description="تسجيل الورديات وحساب الساعات تلقائيًا، بما في ذلك الورديات التي تتجاوز منتصف الليل." actions={<PermissionGuard allow={permissions.daily_labor_create}><Button onClick={()=>setShowForm(true)}><Plus size={16}/> إضافة وردية</Button></PermissionGuard>}/><ErrorState error={error}/>
    <div className={`v22-grid ${canSeeMoney?"cols-5":"cols-2"} labor-stats`}><StatCard label="ساعات العمل" value={`${summary.hours.toFixed(2)} ساعة`}/>{canSeeMoney&&<><StatCard label="إجمالي تكلفة العمالة" value={money(summary.total)}/><StatCard label="المدفوع" value={money(summary.paid)} tone="positive"/><StatCard label="غير المدفوع" value={money(summary.unpaid)} tone="negative"/></>}<StatCard label="عدد الورديات" value={rows.length}/></div>
    <Panel><div className="v22-filters"><Input type="date" value={from} onChange={(e)=>setFrom(e.target.value)} aria-label="من"/><Input type="date" value={to} onChange={(e)=>setTo(e.target.value)} aria-label="إلى"/><Select value={project} onChange={(e)=>setProject(e.target.value)}><option value="">كل المشاريع</option>{data.projects.map((p)=><option key={p.id} value={p.id}>{p.project_name}</option>)}</Select><Select value={group} onChange={(e)=>setGroup(e.target.value)}><option value="none">بدون تجميع</option><option value="worker">تجميع حسب العامل</option><option value="project">تجميع حسب المشروع</option></Select></div>{rows.length?grouped.map(([label,items])=><div className="labor-group" key={label}><h3>{label}<span>{items.length} وردية</span></h3><DataTable headers={canSeeMoney?["العامل","المشروع","التاريخ","الوردية","الساعات","السعر","الإجمالي","الدفع","إجراءات"]:["العامل","المشروع","التاريخ","الوردية","الساعات","إجراءات"]}>{items.map((r)=><tr key={r.id}><td><strong>{r.worker_name}</strong><br/><small>{r.trade||"—"}</small></td><td>{data.projects.find((p)=>p.id===r.project_id)?.project_name||"—"}</td><td>{r.work_date}</td><td>{r.start_time?.slice(0,5)} — {r.end_time?.slice(0,5)}</td><td>{r.total_hours}</td>{canSeeMoney&&<><td>{money(r.hourly_rate)}</td><td><strong>{money(r.total_amount)}</strong></td><td><span className={`payroll-status ${r.payment_status}`}>{PAYMENT_STATUS[r.payment_status]}</span></td></>}<td><div className="v22-actions">{canSeeMoney&&r.payment_status!=="paid"&&permissions.daily_labor_pay&&<Button onClick={()=>setPendingPaid(r)}><Banknote size={14}/> دفع</Button>}{permissions.daily_labor_delete&&<button className="v22-icon-button danger" onClick={()=>remove(r)}><Trash2 size={15}/></button>}</div></td></tr>)}</DataTable></div>):<EmptyState title="لا توجد ورديات مطابقة"/>}</Panel>
    {showForm&&<div className="v22-modal-backdrop"><div className="v22-modal"><h3>تسجيل وردية يومية</h3><DailyLaborForm projects={data.projects} profile={profile} canSeeMoney={canSeeMoney} onCancel={()=>setShowForm(false)} onSaved={async()=>{await refresh("dailyLabor");setShowForm(false)}}/></div></div>}
    <ConfirmDialog open={Boolean(pendingPaid)} title="تأكيد دفع مستحق العامل" description={`تأكيد دفع ${money(pendingPaid?.total_amount)} للعامل ${pendingPaid?.worker_name}.`} confirmLabel="تأكيد الدفع" onCancel={()=>setPendingPaid(null)} onConfirm={async()=>{await markPaid(pendingPaid);setPendingPaid(null)}}/>
  </div>;
}
