import React, { useMemo, useState } from "react";
import { isAdministrativeRole } from "../identity";
import { BadgeCheck, Banknote, Plus, Trash2, UserPlus } from "lucide-react";
import { supabase } from "../supabaseClient";
import { Button, ConfirmDialog, DataTable, EmptyState, ErrorState, Field, Input, money, number, PageTitle, Panel, PermissionGuard, Select, StatCard, TextArea, Toast } from "./shared";
import { calculateNetSalary } from "./calculations";
import { syncMutation } from "./mutations";

const EMPLOYEE_STATUS = { active: "نشط", suspended: "موقوف", resigned: "مستقيل", terminated: "منتهي الخدمة" };
const PAYROLL_STATUS = { draft: "مسودة", approved: "معتمد", paid: "مدفوع" };
const emptyEmployee = { full_name: "", phone: "", job_title: "", department: "", base_salary: 0, housing_allowance: 0, transport_allowance: 0, other_allowance: 0, hire_date: "", status: "active" };

export function EmployeesTab({ data, profile, refresh }) {
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(emptyEmployee); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [search, setSearch] = useState("");
  const employees = data.employees.filter((e) => e.full_name.toLowerCase().includes(search.toLowerCase()) || (e.department || "").toLowerCase().includes(search.toLowerCase()));
  async function submit(e) { e.preventDefault(); setError(""); setSuccess(""); const payload = { ...form, base_salary:number(form.base_salary), housing_allowance:number(form.housing_allowance), transport_allowance:number(form.transport_allowance), other_allowance:number(form.other_allowance), hire_date: form.hire_date || null, created_by:profile.id }; const mutationResult = await supabase.from("employees").insert(payload); const result = await syncMutation({ scope:"employees:create", mutationResult, refetch:()=>refresh("employees") }); if(result.error)return setError(result.error.message); setShowForm(false); setForm(emptyEmployee); setSuccess("تمت إضافة الموظف بنجاح"); }
  async function remove(id) { if(!window.confirm("حذف سجل الموظف؟")) return; setError(""); setSuccess(""); const mutationResult=await supabase.from("employees").delete().eq("id",id); const result=await syncMutation({scope:"employees:delete",mutationResult,refetch:()=>refresh("employees")}); if(result.error)return setError(result.error.message); setSuccess("تم حذف سجل الموظف بنجاح"); }
  return <div><PageTitle eyebrow="الموارد البشرية" title="الموظفون" description="بيانات الموظفين والرواتب الأساسية والبدلات." actions={<Button onClick={()=>setShowForm(true)}><UserPlus size={16}/> موظف جديد</Button>} /><ErrorState error={error}/>
    <Panel><div className="v22-filters"><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو القسم..."/></div>{employees.length ? <DataTable headers={["الموظف","المسمى","القسم","الراتب الأساسي","البدلات","الحالة",""]}>{employees.map((e)=><tr key={e.id}><td><strong>{e.full_name}</strong><br/><small>{e.phone||"—"}</small></td><td>{e.job_title||"—"}</td><td>{e.department||"—"}</td><td>{money(e.base_salary)}</td><td>{money(number(e.housing_allowance)+number(e.transport_allowance)+number(e.other_allowance))}</td><td><span className={`payroll-status ${e.status}`}>{EMPLOYEE_STATUS[e.status]}</span></td><td>{isAdministrativeRole(profile.role)&&<button className="v22-icon-button danger" onClick={()=>remove(e.id)}><Trash2 size={15}/></button>}</td></tr>)}</DataTable> : <EmptyState title="لا يوجد موظفون"/>}</Panel>
    {showForm&&<div className="v22-modal-backdrop"><form className="v22-modal" onSubmit={submit}><h3>إضافة موظف</h3><div className="v22-form-grid"><Field label="الاسم الكامل"><Input required value={form.full_name} onChange={(e)=>setForm({...form,full_name:e.target.value})}/></Field><Field label="الهاتف"><Input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></Field><Field label="المسمى الوظيفي"><Input value={form.job_title} onChange={(e)=>setForm({...form,job_title:e.target.value})}/></Field><Field label="القسم"><Input value={form.department} onChange={(e)=>setForm({...form,department:e.target.value})}/></Field><Field label="الراتب الأساسي"><Input type="number" min="0" value={form.base_salary} onChange={(e)=>setForm({...form,base_salary:e.target.value})}/></Field><Field label="بدل السكن"><Input type="number" min="0" value={form.housing_allowance} onChange={(e)=>setForm({...form,housing_allowance:e.target.value})}/></Field><Field label="بدل النقل"><Input type="number" min="0" value={form.transport_allowance} onChange={(e)=>setForm({...form,transport_allowance:e.target.value})}/></Field><Field label="بدلات أخرى"><Input type="number" min="0" value={form.other_allowance} onChange={(e)=>setForm({...form,other_allowance:e.target.value})}/></Field><Field label="تاريخ التعيين"><Input type="date" value={form.hire_date} onChange={(e)=>setForm({...form,hire_date:e.target.value})}/></Field><Field label="الحالة"><Select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}>{Object.entries(EMPLOYEE_STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field></div><ErrorState error={error}/><div className="v22-actions modal-actions"><Button type="button" variant="ghost" onClick={()=>setShowForm(false)}>إلغاء</Button><Button>حفظ</Button></div></form></div>}
    <Toast message={success} onDismiss={()=>setSuccess("")}/>
  </div>;
}

const initialPayroll = { employee_id:"", payroll_month:new Date().toISOString().slice(0,7), overtime_hours:0, overtime_rate:0, deductions:0, bonuses:0, advances:0, notes:"" };
export function PayrollTab({ data, profile, permissions, refresh }) {
  const [form,setForm]=useState(initialPayroll); const [showForm,setShowForm]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const [status,setStatus]=useState(""); const [pendingPaid,setPendingPaid]=useState(null);
  const rows=useMemo(()=>data.payroll.filter((p)=>(!month||p.payroll_month?.slice(0,7)===month)&&(!status||p.status===status)),[data.payroll,month,status]);
  const totals=useMemo(()=>rows.reduce((a,p)=>({net:a.net+number(p.net_salary),deductions:a.deductions+number(p.deductions),bonuses:a.bonuses+number(p.bonuses),advances:a.advances+number(p.advances)}),{net:0,deductions:0,bonuses:0,advances:0}),[rows]);
  const employee=data.employees.find((e)=>e.id===form.employee_id); const preview=employee?calculateNetSalary({...employee,...form}):0;
  async function create(e){e.preventDefault();setError("");setSuccess("");if(!employee)return setError("اختر الموظف");const payload={employee_id:employee.id,payroll_month:`${form.payroll_month}-01`,base_salary:number(employee.base_salary),housing_allowance:number(employee.housing_allowance),transport_allowance:number(employee.transport_allowance),other_allowance:number(employee.other_allowance),overtime_hours:number(form.overtime_hours),overtime_rate:number(form.overtime_rate),deductions:number(form.deductions),bonuses:permissions.payroll_bonus_manage?number(form.bonuses):0,advances:number(form.advances),notes:form.notes||null,created_by:profile.id};const mutationResult=await supabase.from("payroll").insert(payload);const result=await syncMutation({scope:"payroll:create",mutationResult,refetch:()=>refresh("payroll")});if(result.error)return setError(result.error.message);setShowForm(false);setForm(initialPayroll);setSuccess("تم إنشاء مسير الراتب بنجاح")}
  async function setWorkflow(row,next){setError("");setSuccess("");const mutationResult=await supabase.from("payroll").update({status:next}).eq("id",row.id);const result=await syncMutation({scope:`payroll:${next}`,mutationResult,refetch:()=>refresh("payroll")});if(result.error)setError(result.error.message);else setSuccess(next==="paid"?"تم تسجيل صرف الراتب بنجاح":"تم تحديث حالة الراتب بنجاح");return result;}
  async function remove(row){if(!window.confirm("حذف مسير الراتب؟"))return;setError("");setSuccess("");const mutationResult=await supabase.from("payroll").delete().eq("id",row.id);const result=await syncMutation({scope:"payroll:delete",mutationResult,refetch:()=>refresh("payroll")});if(result.error)return setError(result.error.message);setSuccess("تم حذف مسير الراتب بنجاح");}
  return <div><PageTitle eyebrow="المحاسبة · مسير شهري" title="الرواتب" description="إنشاء واعتماد وصرف الرواتب مع تقارير الخصومات والمكافآت والسلف." actions={<PermissionGuard allow={permissions.payroll_create}><Button onClick={()=>setShowForm(true)}><Plus size={16}/> إنشاء راتب</Button></PermissionGuard>}/><ErrorState error={error}/>
    <div className="v22-grid cols-5 payroll-stats"><StatCard label="صافي الرواتب" value={money(totals.net)}/><StatCard label="الخصومات" value={money(totals.deductions)} tone="negative"/><StatCard label="المكافآت" value={money(totals.bonuses)} tone="positive"/><StatCard label="السلف" value={money(totals.advances)}/><StatCard label="غير مدفوع" value={money(rows.filter((p)=>p.status!=="paid").reduce((s,p)=>s+number(p.net_salary),0))}/></div>
    <Panel><div className="v22-filters"><Input type="month" value={month} onChange={(e)=>setMonth(e.target.value)}/><Select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(PAYROLL_STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></div>{rows.length?<DataTable headers={["الموظف","الشهر","إضافي","خصومات","مكافآت","سلف","الصافي","الحالة","إجراءات"]}>{rows.map((p)=>{const emp=data.employees.find((e)=>e.id===p.employee_id);const canSeeBonus=isAdministrativeRole(profile.role)||p.status!=="draft";return <tr key={p.id}><td>{emp?.full_name||"موظف محذوف"}</td><td>{p.payroll_month?.slice(0,7)}</td><td>{money(p.overtime_amount)}</td><td>{money(p.deductions)}</td><td>{canSeeBonus?money(p.bonuses):"محجوب حتى الاعتماد"}</td><td>{money(p.advances)}</td><td><strong>{money(p.net_salary)}</strong></td><td><span className={`payroll-status ${p.status}`}>{PAYROLL_STATUS[p.status]}</span></td><td><div className="v22-actions"><PermissionGuard allow={p.status==="draft"&&permissions.payroll_approve}><Button onClick={()=>setWorkflow(p,"approved")}><BadgeCheck size={14}/> اعتماد</Button></PermissionGuard><PermissionGuard allow={p.status==="approved"&&permissions.payroll_mark_paid}><Button onClick={()=>setPendingPaid(p)}><Banknote size={14}/> صرف</Button></PermissionGuard>{isAdministrativeRole(profile.role)&&<button className="v22-icon-button danger" onClick={()=>remove(p)}><Trash2 size={15}/></button>}</div></td></tr>})}</DataTable>:<EmptyState title="لا يوجد مسير رواتب للشهر المحدد"/>}</Panel>
    {showForm&&<div className="v22-modal-backdrop"><form className="v22-modal" onSubmit={create}><h3>إنشاء مسير راتب</h3><div className="v22-form-grid"><Field label="الموظف"><Select required value={form.employee_id} onChange={(e)=>setForm({...form,employee_id:e.target.value})}><option value="">اختر الموظف</option>{data.employees.filter((e)=>e.status==="active").map((e)=><option key={e.id} value={e.id}>{e.full_name}</option>)}</Select></Field><Field label="الشهر"><Input required type="month" value={form.payroll_month} onChange={(e)=>setForm({...form,payroll_month:e.target.value})}/></Field><Field label="ساعات إضافية"><Input type="number" min="0" step=".25" value={form.overtime_hours} onChange={(e)=>setForm({...form,overtime_hours:e.target.value})}/></Field><Field label="سعر الساعة الإضافية"><Input type="number" min="0" value={form.overtime_rate} onChange={(e)=>setForm({...form,overtime_rate:e.target.value})}/></Field><Field label="الخصومات"><Input type="number" min="0" value={form.deductions} onChange={(e)=>setForm({...form,deductions:e.target.value})}/></Field><PermissionGuard allow={permissions.payroll_bonus_manage}><Field label="المكافآت"><Input type="number" min="0" value={form.bonuses} onChange={(e)=>setForm({...form,bonuses:e.target.value})}/></Field></PermissionGuard><Field label="السلف"><Input type="number" min="0" value={form.advances} onChange={(e)=>setForm({...form,advances:e.target.value})}/></Field><Field label="ملاحظات" wide><TextArea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field></div>{employee&&<div className="payroll-preview"><span>صافي الراتب المتوقع</span><strong>{money(preview)}</strong></div>}<ErrorState error={error}/><div className="v22-actions modal-actions"><Button type="button" variant="ghost" onClick={()=>setShowForm(false)}>إلغاء</Button><Button>حفظ كمسودة</Button></div></form></div>}
    <ConfirmDialog open={Boolean(pendingPaid)} title="تأكيد صرف الراتب" description={`سيتم تعليم راتب ${data.employees.find((e)=>e.id===pendingPaid?.employee_id)?.full_name||"الموظف"} بقيمة ${money(pendingPaid?.net_salary)} كمدفوع. هل تم تنفيذ التحويل بالفعل؟`} confirmLabel="نعم، تم الصرف" onCancel={()=>setPendingPaid(null)} onConfirm={async()=>{const result=await setWorkflow(pendingPaid,"paid");if(!result.error)setPendingPaid(null)}}/>
    <Toast message={success} onDismiss={()=>setSuccess("")}/>
  </div>;
}
