import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, ChevronDown, ChevronUp, Copy, FileDiff, Plus, RefreshCw, Save, ShieldCheck, Trash2 } from "lucide-react";
import { supabase } from "../supabaseClient";
import { Button, DataTable, EmptyState, ErrorState, Field, Input, Panel, Select, StatCard, SuccessState, TextArea } from "./shared";
import { BUDGET_CATEGORIES, BUDGET_CATEGORY_GROUPS, BUDGET_STATUSES, categoryGroupTotals } from "./projectBudgetDomain";
import "./projectBudget.css";

const EMPTY_ITEM = { id:"",section_id:"",category:"wood",item_code:"",description:"",quantity:1,unit:"وحدة",unit_cost:0,waste_percentage:0,notes:"",sequence:0,milestone_id:"",cost_center_reference:"",purchase_request_reference:"" };
const EMPTY_SECTION = { id:"",section_key:"",section_name:"",sequence:0,notes:"" };
const financialFields = ["unit_cost","estimated_cost","waste_amount","total_with_waste"];
const DEFAULT_SECTIONS = [["materials","المواد"],["labor","العمالة"],["production","الإنتاج"],["equipment","المعدات"],["logistics","النقل واللوجستيات"],["other","مصروفات أخرى"]];

function budgetMoney(value,currency="SAR") { return `${Number(value||0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`; }
function versionLabel(version) { return `نسخة ${version.version_number} · ${BUDGET_STATUSES[version.status] || version.status}`; }

export function BudgetSummary({ version,items,canViewFinancials }) {
  const groups=categoryGroupTotals(items); const currency=version?.currency || "SAR";
  if(!version) return null;
  return <div className="budget-summary-grid">
    {Object.entries({materials:"تكلفة المواد",labor:"تكلفة العمالة",production:"تكلفة الإنتاج",logistics:"النقل واللوجستيات",equipment:"المعدات",other:"المصروفات الأخرى"}).map(([key,label])=><StatCard key={key} label={label} value={canViewFinancials?budgetMoney(groups[key],currency):"محجوبة"}/>)}
    <StatCard label="الاحتياطي" value={canViewFinancials?budgetMoney(version.contingency_amount,currency):"محجوب"}/><StatCard label="التكاليف غير المباشرة" value={canViewFinancials?budgetMoney(version.overhead_amount,currency):"محجوبة"}/>
    <StatCard label="إجمالي التكلفة المتوقعة" value={canViewFinancials?budgetMoney(version.expected_total_cost,currency):"محجوب"} tone="positive"/><StatCard label="الربح المستهدف" value={canViewFinancials?budgetMoney(version.target_profit_amount,currency):"محجوب"}/><StatCard label="سعر البيع المستهدف" value={canViewFinancials?budgetMoney(version.target_sale_price,currency):"محجوب"}/>
  </div>;
}

export function BudgetItemDialog({ open,item,sections,milestones,canViewFinancials,onChange,onSave,onCancel,busy }) {
  if(!open) return null;
  return <Panel className="budget-editor"><h4>{item.id?"تعديل بند الميزانية":"إضافة بند ميزانية"}</h4><div className="v22-form-grid">
    <Field label="القسم"><Select value={item.section_id} onChange={(e)=>onChange({...item,section_id:e.target.value})}>{sections.map((row)=><option key={row.id} value={row.id}>{row.section_name}</option>)}</Select></Field>
    <Field label="البند"><Select value={item.category} onChange={(e)=>onChange({...item,category:e.target.value})}>{Object.entries(BUDGET_CATEGORY_GROUPS).map(([key,group])=><optgroup key={key} label={group.label}>{Object.entries(group.items).map(([value,label])=><option key={value} value={value}>{label}</option>)}</optgroup>)}</Select></Field>
    <Field label="كود البند"><Input value={item.item_code||""} onChange={(e)=>onChange({...item,item_code:e.target.value})}/></Field><Field label="الوصف"><Input required value={item.description||""} onChange={(e)=>onChange({...item,description:e.target.value})}/></Field>
    <Field label="الكمية"><Input type="number" min="0" step="0.0001" value={item.quantity} onChange={(e)=>onChange({...item,quantity:e.target.value})}/></Field><Field label="الوحدة"><Input value={item.unit||""} onChange={(e)=>onChange({...item,unit:e.target.value})}/></Field>
    {canViewFinancials&&<><Field label="تكلفة الوحدة"><Input type="number" min="0" step="0.01" value={item.unit_cost} onChange={(e)=>onChange({...item,unit_cost:e.target.value})}/></Field><Field label="الهالك %"><Input type="number" min="0" max="100" step="0.01" value={item.waste_percentage} onChange={(e)=>onChange({...item,waste_percentage:e.target.value})}/></Field></>}
    <Field label="مرحلة المشروع"><Select value={item.milestone_id||""} onChange={(e)=>onChange({...item,milestone_id:e.target.value})}><option value="">بدون مرحلة</option>{milestones.map((row)=><option key={row.id} value={row.id}>{row.title}</option>)}</Select></Field><Field label="ملاحظات" wide><TextArea value={item.notes||""} onChange={(e)=>onChange({...item,notes:e.target.value})}/></Field>
  </div><div className="v22-actions"><Button variant="ghost" onClick={onCancel}>إلغاء</Button><Button disabled={busy||!item.description?.trim()||!item.section_id} onClick={onSave}><Save size={15}/> حفظ البند</Button></div></Panel>;
}

export function BudgetItemTable({ items,canEdit,canViewFinancials,currency,onEdit,onDuplicate,onDelete,onMove }) {
  if(!items.length) return <EmptyState title="لا توجد بنود في هذا القسم" description="اضغط «إضافة بند» واكتب الكمية وتكلفة الوحدة."/>;
  return <DataTable headers={["البند","الوصف","الكمية","الوحدة",...(canViewFinancials?["تكلفة الوحدة","الهالك","الإجمالي"]:[]),"ملاحظات",...(canEdit?["إجراءات"]:[])]}>{items.map((row,index)=><tr key={row.id}><td>{BUDGET_CATEGORIES[row.category]||row.category}</td><td><strong>{row.description}</strong>{row.item_code&&<small>{row.item_code}</small>}</td><td>{row.quantity}</td><td>{row.unit}</td>{canViewFinancials&&<><td>{budgetMoney(row.unit_cost,currency)}</td><td>{row.waste_percentage}%</td><td>{budgetMoney(row.total_with_waste,currency)}</td></>}<td>{row.notes||"—"}</td>{canEdit&&<td><div className="budget-row-actions"><button title="لأعلى" disabled={index===0} onClick={()=>onMove(row,-1)}><ChevronUp size={14}/></button><button title="لأسفل" disabled={index===items.length-1} onClick={()=>onMove(row,1)}><ChevronDown size={14}/></button><button title="تعديل" onClick={()=>onEdit(row)}>تعديل</button><button title="تكرار" onClick={()=>onDuplicate(row)}><Copy size={14}/></button><button title="حذف" onClick={()=>onDelete(row)}><Trash2 size={14}/></button></div></td>}</tr>)}</DataTable>;
}

export function BudgetSections({ sections,items,version,canEdit,canViewFinancials,onAddItem,onEditItem,onDuplicateItem,onDeleteItem,onMoveItem }) {
  const [collapsed,setCollapsed]=useState({}); if(!sections.length) return null;
  return <div className="budget-sections">{sections.map((section)=><Panel key={section.id} className="budget-section"><header><button className="budget-collapse" onClick={()=>setCollapsed((current)=>({...current,[section.id]:!current[section.id]}))}>{collapsed[section.id]?<ChevronDown size={16}/>:<ChevronUp size={16}/>}<strong>{section.section_name}</strong></button><div>{canViewFinancials&&<b>{budgetMoney(section.subtotal,version.currency)}</b>}{canEdit&&<Button onClick={()=>onAddItem(section.id)}><Plus size={14}/> إضافة بند</Button>}</div></header>{!collapsed[section.id]&&<BudgetItemTable items={items.filter((row)=>row.section_id===section.id).sort((a,b)=>a.sequence-b.sequence)} canEdit={canEdit} canViewFinancials={canViewFinancials} currency={version.currency} onEdit={onEditItem} onDuplicate={onDuplicateItem} onDelete={onDeleteItem} onMove={onMoveItem}/>}</Panel>)}</div>;
}

export function BudgetApprovalPanel({ version,permissions,busy,onSubmit,onApprove,onReject,onCancel,onCopy,canSubmit,submitHint }) {
  if(!version) return null; const draft=version.status==="draft"; const submitted=version.status==="submitted";
  return <Panel className="budget-approval"><div><h4>الموافقات</h4><span className={`budget-status ${version.status}`}>{BUDGET_STATUSES[version.status]}</span>{draft&&submitHint&&<p className="budget-submit-hint">{submitHint}</p>}</div><div className="v22-actions">
    {draft&&permissions.project_budget_submit&&<Button disabled={busy||!canSubmit} onClick={onSubmit}>إرسال للاعتماد</Button>}
    {submitted&&permissions.project_budget_approve&&<Button disabled={busy} onClick={onApprove}><Check size={15}/> اعتماد الميزانية</Button>}
    {submitted&&permissions.project_budget_reject&&<Button variant="danger" disabled={busy} onClick={onReject}>رفض</Button>}
    {draft&&permissions.project_budget_edit&&<Button variant="danger" disabled={busy} onClick={onCancel}>إلغاء المسودة</Button>}
    {version.status!=="draft"&&permissions.project_budget_create&&<Button variant="ghost" disabled={busy} onClick={onCopy}><Copy size={15}/> نسخ لمسودة جديدة</Button>}
  </div></Panel>;
}

export function BudgetVersionHistory({ versions,selectedId,onSelect,onCopy }) { return <Panel><h4>النسخ السابقة</h4>{versions.length?<div className="budget-version-list">{versions.map((row)=><button key={row.id} className={selectedId===row.id?"active":""} onClick={()=>onSelect(row.id)}><span>{versionLabel(row)}</span><small>{row.approved_at?new Date(row.approved_at).toLocaleDateString("ar-SA"):new Date(row.created_at).toLocaleDateString("ar-SA")}</small>{row.status!=="draft"&&<Copy size={13} onClick={(event)=>{event.stopPropagation();onCopy(row);}}/>}</button>)}</div>:<EmptyState title="لا توجد نسخ ميزانية"/>}</Panel>; }
export function BudgetVersionCompare({ versions,comparison,busy,onCompare }) { const [left,setLeft]=useState(""); const [right,setRight]=useState(""); return <Panel className="budget-compare"><h4>مقارنة النسخ</h4><div className="budget-compare-controls"><Select value={left} onChange={(e)=>setLeft(e.target.value)}><option value="">النسخة القديمة</option>{versions.map((row)=><option key={row.id} value={row.id}>{versionLabel(row)}</option>)}</Select><Select value={right} onChange={(e)=>setRight(e.target.value)}><option value="">النسخة الجديدة</option>{versions.map((row)=><option key={row.id} value={row.id}>{versionLabel(row)}</option>)}</Select><Button disabled={busy||!left||!right||left===right} onClick={()=>onCompare(left,right)}><FileDiff size={15}/> مقارنة</Button></div>{comparison&&<div className="budget-variance"><span>القديم: {comparison.old_total??"محجوب"}</span><span>الجديد: {comparison.new_total??"محجوب"}</span><strong>الفرق: {comparison.variance_amount??"محجوب"}</strong></div>}</Panel>; }
export function ActivationReadinessPanel({ readiness,permissions,busy,onReload,onOverride }) { return <Panel className="activation-readiness"><header><div><h4>جاهزية تفعيل المشروع</h4><p>{readiness?.ready?"كل الشروط مكتملة. ارجع إلى «نظرة عامة» لتفعيل المشروع.":"أكمل البنود الحاجبة بالأسفل. مدير المشروع يُحدد من تبويب «الفريق»."}</p></div><Button variant="ghost" onClick={onReload}><RefreshCw size={14}/> تحديث</Button></header>{readiness?.checks?.map((check)=><div key={check.key} className={check.passed?"passed":"failed"}>{check.passed?<Check size={15}/>:<AlertTriangle size={15}/>}<span>{check.label}</span>{check.blocking&&<small>حاجب</small>}</div>)}{!readiness?.ready&&permissions.project_budget_override_activation&&<Button variant="danger" disabled={busy} onClick={onOverride}><ShieldCheck size={15}/> تجاوز Owner استثنائي</Button>}</Panel>; }
export function BudgetTemplatePicker({ templates,permissions,busy,onCreateFrom,onSaveTemplate }) { const [templateId,setTemplateId]=useState(""); if(!permissions.project_budget_create&&!permissions.project_budget_manage_templates) return null; return <Panel><h4>قوالب الميزانية</h4><div className="budget-template-actions"><Select value={templateId} onChange={(e)=>setTemplateId(e.target.value)}><option value="">اختر قالبًا</option>{templates.map((row)=><option key={row.id} value={row.id}>{row.template_name}</option>)}</Select><Button disabled={busy||!templateId} onClick={()=>onCreateFrom(templateId)}>إنشاء من القالب</Button>{permissions.project_budget_manage_templates&&<Button variant="ghost" disabled={busy} onClick={onSaveTemplate}>حفظ النسخة كقالب</Button>}</div></Panel>; }

export function ProjectBudgetTab({ project,data,permissions,refresh }) {
  const [payload,setPayload]=useState({versions:[],sections:[],items:[],templates:[],can_view_financials:false}); const [selectedId,setSelectedId]=useState(""); const [item,setItem]=useState(EMPTY_ITEM); const [showItem,setShowItem]=useState(false); const [section,setSection]=useState(EMPTY_SECTION); const [showSection,setShowSection]=useState(false); const [comparison,setComparison]=useState(null); const [readiness,setReadiness]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const selected=payload.versions.find((row)=>row.id===selectedId)||payload.versions[0]; const sections=payload.sections.filter((row)=>row.budget_version_id===selected?.id).sort((a,b)=>a.sequence-b.sequence); const items=payload.items.filter((row)=>row.budget_version_id===selected?.id); const canViewFinancials=Boolean(payload.can_view_financials&&permissions.project_budget_view_financials); const canEdit=Boolean(selected?.status==="draft"&&permissions.project_budget_edit);
  const load=useCallback(async()=>{setError("");const [budgetResult,readinessResult]=await Promise.all([supabase.rpc("get_project_budget_visible",{target_project:project.id,target_version:null}),supabase.rpc("get_project_activation_readiness",{target_project:project.id})]);if(budgetResult.error)setError(budgetResult.error.message);else{setPayload(budgetResult.data||{versions:[],sections:[],items:[],templates:[]});setSelectedId((current)=>current&&budgetResult.data?.versions?.some((row)=>row.id===current)?current:(budgetResult.data?.versions?.find((row)=>row.status==="draft")||budgetResult.data?.versions?.find((row)=>row.status==="approved")||budgetResult.data?.versions?.[0])?.id||"");}if(!readinessResult.error)setReadiness(readinessResult.data);},[project.id]); useEffect(()=>{void load();},[load]);
  async function run(name,args,message,{reload=true}={}){setBusy(true);setError("");setSuccess("");try{const result=await supabase.rpc(name,args);if(result.error)throw result.error;if(reload){await Promise.all([load(),refresh("projects"),refresh("projectActivities")]);}setSuccess(message);return result.data;}catch(issue){setError(issue.message||"تعذر تنفيذ الإجراء");return null;}finally{setBusy(false);}}
  async function createDraft(){const created=await run("create_project_budget_draft",{target_project:project.id,currency_code:"SAR"},"تم إنشاء مسودة الميزانية.");if(created)setSelectedId(created.id);} async function saveItem(){const payloadItem={...item,budget_version_id:selected.id,unit_cost:canViewFinancials?item.unit_cost:undefined,waste_percentage:canViewFinancials?item.waste_percentage:undefined};for(const key of financialFields)if(payloadItem[key]===undefined)delete payloadItem[key];const saved=await run("save_project_budget_item",{payload:payloadItem},"تم حفظ البند.");if(saved){setShowItem(false);setItem(EMPTY_ITEM);}} async function deleteItem(row){if(window.confirm(`حذف البند «${row.description}»؟`))await run("delete_project_budget_draft_item",{target_item:row.id},"تم حذف البند.");}
  async function moveItem(row,direction){const same=items.filter((entry)=>entry.section_id===row.section_id).sort((a,b)=>a.sequence-b.sequence);const index=same.findIndex((entry)=>entry.id===row.id);const swap=same[index+direction];if(!swap)return;const order=same.map((entry,position)=>({id:entry.id,section_id:entry.section_id,sequence:entry.id===row.id?index+direction:entry.id===swap.id?index:position}));await run("reorder_project_budget_items",{target_version:selected.id,ordered_items:order},"تم تغيير ترتيب البنود.");}
  async function saveSection(){const saved=await run("save_project_budget_section",{payload:{...section,budget_version_id:selected.id}},"تم حفظ القسم.");if(saved){setShowSection(false);setSection(EMPTY_SECTION);}}
  async function startBudget(){setBusy(true);setError("");setSuccess("");try{let firstSection=null;for(let index=0;index<DEFAULT_SECTIONS.length;index+=1){const [sectionKey,sectionName]=DEFAULT_SECTIONS[index];const result=await supabase.rpc("save_project_budget_section",{payload:{...EMPTY_SECTION,budget_version_id:selected.id,section_key:sectionKey,section_name:sectionName,sequence:index}});if(result.error)throw result.error;if(!firstSection)firstSection=result.data;}await load();setSuccess("تم تجهيز أقسام الميزانية. ابدأ بإضافة أول بند.");if(firstSection?.id){setItem({...EMPTY_ITEM,section_id:firstSection.id});setShowItem(true);}}catch(issue){setError(issue.message||"تعذر تجهيز أقسام الميزانية");}finally{setBusy(false);}}
  async function submitBudget(){if(!sections.length||!items.length)return setError("أضف قسمًا وبند ميزانية واحدًا على الأقل قبل الإرسال للاعتماد.");await run("submit_project_budget",{target_version:selected.id},"تم إرسال الميزانية للاعتماد.");}
  async function saveHeader(){const notes=window.prompt("ملاحظات الميزانية",selected.notes||"");if(notes===null)return;await run("update_project_budget_header",{target_version:selected.id,payload:{notes}},"تم حفظ ملاحظات الميزانية.");} async function copyVersion(version=selected){const created=await run("copy_project_budget_version",{source_version:version.id},"تم إنشاء مسودة من النسخة المختارة.");if(created)setSelectedId(created.id);} async function compare(left,right){const result=await run("compare_project_budget_versions",{left_version:left,right_version:right},"تمت المقارنة.",{reload:false});if(result)setComparison(result);} async function reject(){const reason=window.prompt("سبب الرفض الإجباري");if(reason?.trim())await run("reject_project_budget",{target_version:selected.id,rejection_reason:reason.trim()},"تم رفض النسخة مع حفظ السبب.");} async function cancel(){const reason=window.prompt("سبب إلغاء المسودة (اختياري)")||null;await run("cancel_project_budget_draft",{target_version:selected.id,reason},"تم إلغاء المسودة.");} async function override(){const reason=window.prompt("سبب التجاوز الاستثنائي الإجباري");if(reason?.trim())await run("override_project_activation_budget_requirement",{target_project:project.id,override_reason:reason.trim()},"تم تسجيل التجاوز الاستثنائي.");} async function saveTemplate(){if(!selected||!["approved","superseded"].includes(selected.status))return setError("اختر نسخة معتمدة أو مستبدلة لإنشاء قالب.");const name=window.prompt("اسم القالب");if(name?.trim())await run("create_budget_template_from_version",{source_version:selected.id,template_name:name.trim(),template_type:"custom"},"تم إنشاء القالب.");} async function createFromTemplate(templateId){const created=await run("create_budget_from_template",{target_project:project.id,target_template:templateId},"تم إنشاء مسودة من القالب.");if(created)setSelectedId(created.id);}
  if(!permissions.project_budget_view)return <Panel className="workspace-no-permission"><ShieldCheck size={24}/>لا تملك صلاحية عرض الميزانية التقديرية.</Panel>; const canSubmit=sections.length>0&&items.length>0; const submitHint=canSubmit?"الميزانية جاهزة للإرسال بعد مراجعة البنود.":"أضف بند ميزانية واحدًا على الأقل قبل الإرسال.";
  return <div className="project-budget" dir="rtl"><ErrorState error={error}/><SuccessState message={success}/><div className="budget-toolbar"><div><h3>الميزانية التقديرية</h3><p>الترتيب: جهّز الأقسام ← أضف البنود والكميات والتكاليف ← أرسل للاعتماد ← اعتمد الميزانية ← أكمل جاهزية المشروع.</p></div><div className="v22-actions"><Button variant="ghost" onClick={load}><RefreshCw size={15}/> تحديث</Button>{permissions.project_budget_create&&<Button disabled={busy} onClick={createDraft}><Plus size={15}/> مسودة جديدة</Button>}</div></div>
    {!payload.versions.length?<><Panel><EmptyState title="لم تُنشأ ميزانية تقديرية" description="أنشئ أول مسودة ثم أضف البنود قبل الاعتماد."/></Panel><BudgetTemplatePicker templates={payload.templates} permissions={permissions} busy={busy} onCreateFrom={createFromTemplate} onSaveTemplate={saveTemplate}/></>:<><div className="budget-layout"><main><div className="budget-version-head"><Select value={selected?.id||""} onChange={(e)=>setSelectedId(e.target.value)}>{payload.versions.map((row)=><option key={row.id} value={row.id}>{versionLabel(row)}</option>)}</Select><span className={`budget-status ${selected?.status}`}>{BUDGET_STATUSES[selected?.status]}</span>{canEdit&&<><Button variant="ghost" onClick={saveHeader}>الملاحظات</Button><Button variant="ghost" onClick={()=>{setSection({...EMPTY_SECTION,sequence:sections.length});setShowSection(true);}}><Plus size={14}/> قسم جديد</Button></>}</div>
      {canEdit&&!sections.length&&<Panel className="budget-start-panel"><h4>ابدأ إدخال الميزانية</h4><p>جهّز أقسام المواد والعمالة والإنتاج والمعدات والنقل والمصروفات، وبعدها ستظهر أزرار «إضافة بند» داخل كل قسم.</p><Button disabled={busy} onClick={startBudget}><Plus size={15}/> تجهيز الأقسام وكتابة أول بند</Button></Panel>}
      <BudgetSummary version={selected} items={items} canViewFinancials={canViewFinancials}/><BudgetApprovalPanel version={selected} permissions={permissions} busy={busy} onSubmit={submitBudget} onApprove={()=>run("approve_project_budget",{target_version:selected.id},"تم اعتماد الميزانية.")} onReject={reject} onCancel={cancel} onCopy={()=>copyVersion(selected)} canSubmit={canSubmit} submitHint={submitHint}/>
      {showSection&&<Panel className="budget-editor"><h4>قسم الميزانية</h4><div className="v22-form-grid"><Field label="مفتاح القسم"><Input value={section.section_key} onChange={(e)=>setSection({...section,section_key:e.target.value})}/></Field><Field label="اسم القسم"><Input value={section.section_name} onChange={(e)=>setSection({...section,section_name:e.target.value})}/></Field><Field label="الترتيب"><Input type="number" min="0" value={section.sequence} onChange={(e)=>setSection({...section,sequence:e.target.value})}/></Field><Field label="ملاحظات"><Input value={section.notes||""} onChange={(e)=>setSection({...section,notes:e.target.value})}/></Field></div><div className="v22-actions"><Button variant="ghost" onClick={()=>setShowSection(false)}>إلغاء</Button><Button disabled={busy||!section.section_key.trim()||!section.section_name.trim()} onClick={saveSection}>حفظ</Button></div></Panel>}
      <BudgetItemDialog open={showItem} item={item} sections={sections} milestones={data.projectMilestones.filter((row)=>row.project_id===project.id)} canViewFinancials={canViewFinancials} onChange={setItem} onSave={saveItem} onCancel={()=>setShowItem(false)} busy={busy}/><BudgetSections sections={sections} items={items} version={selected} canEdit={canEdit} canViewFinancials={canViewFinancials} onAddItem={(sectionId)=>{setItem({...EMPTY_ITEM,section_id:sectionId,sequence:items.filter((row)=>row.section_id===sectionId).length});setShowItem(true);}} onEditItem={(row)=>{setItem(row);setShowItem(true);}} onDuplicateItem={(row)=>{setItem({...row,id:"",item_code:row.item_code?`${row.item_code}-COPY`:"",description:`${row.description} — نسخة`,sequence:row.sequence+1});setShowItem(true);}} onDeleteItem={deleteItem} onMoveItem={moveItem}/></main><aside><BudgetVersionHistory versions={payload.versions} selectedId={selected?.id} onSelect={setSelectedId} onCopy={copyVersion}/><ActivationReadinessPanel readiness={readiness} permissions={permissions} busy={busy} onReload={load} onOverride={override}/><BudgetTemplatePicker templates={payload.templates} permissions={permissions} busy={busy} onCreateFrom={createFromTemplate} onSaveTemplate={saveTemplate}/></aside></div><BudgetVersionCompare versions={payload.versions} comparison={comparison} busy={busy} onCompare={compare}/></>}
  </div>;
}
